### PR TITLE
Fix: TS error on Cell prop without Query variable

### LINKED ISSUE #3416: Cell Input props are expecting type `never` if there's no Query variable
If there's a Cell with a query that's doesn't need any variable AND we need some props for the Success component, it results in TS error.
Screenshot 2021-09-22 at 9 55 05 PM
 
This happens because when Graphql Code Gen doesn't finds any variable it creates this type:
Screenshot 2021-09-22 at 9 56 06 PM

and we use `Success & GraphQLVariable` type:
Screenshot 2021-09-22 at 10 15 36 PM

Possible steps to fix:
- Either somehow disable this type in codegen
- Or Comeup with type which removes this behavior

### PR DESCRIPTION
**Pull request by callingmedic911**
Closes #3416.

This PR:
- Creates a new utility type for Cell Input in `createCell.tsx`, which is just an extension of mirror-cell exisiting`CellInput` type that handles if there's no Query variable.
- Modifies `mirror-cell` template to use this utility type instead.
- Updates a test.

### CODE REVIEW

File: packages/internal/src/generate/templates/mirror-cell.d.ts.template [hunk 1]
```diff
@@ -10,6 +10,6 @@ export * from './${name}'
 type CellInputs = Omit<
   ComponentProps<SuccessType>,
   keyof QueryOperationResult | keyof ${queryResultType} | 'updating'
-> & ${queryVariablesType}
+> & (${queryVariablesType} extends Exact<{ [key: string]: never }> ? unknown : ${queryVariablesType})
```
Comment (dac09) [inline packages/internal/src/generate/templates/mirror-cell.d.ts.template:13]: What I was thinking also - but two things:
a) Do we need to check for Exact ?
b) I don't think `unknown` is correct, it should be `{}` or some sort of empty type

Comment (dac09) [reply packages/internal/src/generate/templates/mirror-cell.d.ts.template:13]: c) Lets move this into a utility type

**Comment by callingmedic911** [comment]
@dac09 All set.

**Review by dac09 — APPROVED** [review]
