### PR TITLE
Fix: type issue on the dbAuth generated pages

### LINKED ISSUE #3067: The scaffold template for Auth page has some Typing issues
image

image

image

### PR DESCRIPTION
**Pull request by Albert-Gao**
close #3067

### CODE REVIEW

File: packages/cli/src/commands/generate/dbAuth/templates/login.tsx.template [hunk 1]
```diff
@@ -21,13 +21,13 @@ const LoginPage = () => {
...
 
-  const usernameRef = useRef()
+  const usernameRef = useRef<HTMLInputElement>(null)
   useEffect(() => {
     usernameRef.current.focus()
   }, [])
 
   const onSubmit = async (data) => {
-    const response = await logIn({ ...data })
+    const response: any = await logIn({ ...data })
```
Comment (Albert-Gao) [inline packages/cli/src/commands/generate/dbAuth/templates/login.tsx.template:30]: Just a quick fix, the decent fix should be proper type the logIn method, but does this `logIn` being used for all scenarios and some of them do return while some of them are not? That gonna make it more interesting...

**Comment by cannikin** [comment]
I'd love to approve this, but I would have no idea if this fix is working or not (types are the bane of my existence). Can I substitute @dac09 for me? :)

File: packages/cli/src/commands/generate/dbAuth/templates/login.tsx.template [hunk 2]
```diff
@@ -21,13 +21,13 @@ const LoginPage = () => {
     }
   }, [isAuthenticated])
 
-  const usernameRef = useRef()
+  const usernameRef = useRef<HTMLInputElement>(null)
```
Comment (dac09) [inline packages/cli/src/commands/generate/dbAuth/templates/login.tsx.template:24]: Empty brackets here should do, no? 
```suggestion
  const usernameRef = useRef<HTMLInputElement>()
```

File: packages/cli/src/commands/generate/dbAuth/templates/login.tsx.template (hunk 1 above)
Comment (dac09) [reply packages/cli/src/commands/generate/dbAuth/templates/login.tsx.template:30]: I don't think we need to type the response here, the type can probably be inferred from the login method - which I suppose currently is `any`.

File: packages/cli/src/commands/generate/dbAuth/templates/signup.tsx.template [hunk 3]
```diff
@@ -22,13 +22,13 @@ const SignupPage = () => {
   }, [isAuthenticated])
```
Comment (dac09) [inline packages/cli/src/commands/generate/dbAuth/templates/signup.tsx.template:23]: Same comments as login.tsx

File: packages/cli/src/commands/generate/dbAuth/templates/login.tsx.template (hunk 1 above)
Comment (Albert-Gao) [reply packages/cli/src/commands/generate/dbAuth/templates/login.tsx.template:30]: You are right, should be inferred, the current type is `void` which causes the problem.

this `any` is just for removing that annoying red underline in the IDE xD,

File: packages/cli/src/commands/generate/dbAuth/templates/login.tsx.template (hunk 2 above)
Comment (Albert-Gao) [reply packages/cli/src/commands/generate/dbAuth/templates/login.tsx.template]: done :)

File: packages/cli/src/commands/generate/dbAuth/templates/signup.tsx.template (hunk 3 above)
Comment (Albert-Gao) [reply packages/cli/src/commands/generate/dbAuth/templates/signup.tsx.template:23]: done :)

File: packages/cli/src/commands/generate/dbAuth/templates/login.tsx.template (hunk 1 above)
Comment (dac09) [reply packages/cli/src/commands/generate/dbAuth/templates/login.tsx.template:30]: Gotcha - let me check the typings for useAuth :)

Comment (dac09) [reply packages/cli/src/commands/generate/dbAuth/templates/login.tsx.template:30]: Albert, what do you think of modifying the return type in https://github.com/redwoodjs/redwood/blob/main/packages/auth/src/AuthProvider.tsx to be `Promise<any>`? 

I have plans to improve these typings, but will have to wait a little

Comment (Albert-Gao) [reply packages/cli/src/commands/generate/dbAuth/templates/login.tsx.template:30]: good idea, that would be a better fix since this is the source. Promise<any> would be better because unknown means the we have to cast it when use it.

We can just let that function return Promise<any> and properly type it when the API design is finalized.

**Review by dac09 — CHANGES_REQUESTED** [review]
Awaiting changes to AuthProvider type

**Comment by Albert-Gao** [comment]
Done :) Sorry was sleeping yesterday @dac09

**Comment by dac09** [comment]
Haha no worries @Albert-Gao - just marked the PR to stay organised. Appreciate this - will review in the morning after my sleep :)

**Comment by Albert-Gao** [comment]
image

Tried, updated the type to `Promise<any>` solved the problem

**Review by dac09 — APPROVED** [review]

File: packages/auth/src/AuthProvider.tsx [hunk 4]
```diff
@@ -20,9 +20,9 @@ export interface AuthContextInterface {
   currentUser: null | CurrentUser
   /* The user's metadata from the auth provider */
   userMetadata: null | SupportedUserMetadata
-  logIn(options?: unknown): Promise<void>
+  logIn(options?: unknown): Promise<any>
   logOut(options?: unknown): Promise<void>
```
Comment (dac09) [inline packages/auth/src/AuthProvider.tsx:24]:
```suggestion
  logOut(options?: unknown): Promise<any>
```

**Comment by dac09** [comment]
Cheers @Albert-Gao! 🚀

**Comment by Albert-Gao** [comment]
My pleasure 😀
