### PR TITLE
Router: Populate `routes` for tests

### LINKED ISSUE #2131: Router seems not to be working in testing
I have a very straight forward test (Just checking if no error is thrown), it renders a link on that page, in the browser this works, but in the tests I get this error:

```
Error: Uncaught [TypeError: _router.routes.signin is not a function]
```

I'm wondering if this is something that just me is seeing, or that a bug might have slipped in when we introduced <Set> into the router. (This worked before that upgrade)

### PR DESCRIPTION
**Pull request by Tobbe**
We have a separate `<MockRouter>` that we use instead of the real `<Router>` when running tests in RW apps (not RW framework). This MockRouter is now updated to reflect the rewrite of the real Router.

Fixes #2131

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
@Tobbe I upgraded to this PR, but the problem seems to be still there. Do I need to make changes to my tests to make this work?

**Comment by jvanbaarsen** [comment]
Hm I just notice that the upgrade command doesn't seem to have worked :/ Still have the old MockRouter

**Comment by Tobbe** [comment]
> Hm I just notice that the upgrade command doesn't seem to have worked :/ Still have the old MockRouter

I just tried, and noticed the same 🙁  That's a problem with the `upgrade --pr` command. 
Try this! `yarn add -DW https://rw-pr-redwoodjs-com.s3.amazonaws.com/2133/redwoodjs-testing-0.28.1-ecd5fe7.tgz` That worked for me 👍

**Review by jvanbaarsen — APPROVED** [review]
Great, tested this locally and it works 🔥

**Comment by Tobbe** [comment]
> Great, tested this locally and it works 🔥

Thanks for tesing 🙏

**Review by peterp — APPROVED** [review]

File: packages/testing/src/MockRouter.tsx [hunk 1]
```diff
@@ -3,35 +3,33 @@ import React from 'react'
...
+
+  flatChildArray.forEach((child) => {
+    if (isRoute(child)) {
+      const { name, path } = child.props
 
-  const normalRoutes = (React.Children.toArray(
-    children
-  ) as React.ReactElement[]).filter((child) => child.type === Route)
+      if (path) {
+        if (name && path) {
```
Comment (Tobbe) [inline packages/testing/src/MockRouter.tsx:27]: Err, this looks weird... Let me have another look at this

**Comment by Tobbe** [comment]
@jvanbaarsen This has been release in patch release 0.28.2
