### PR TITLE
Hotfix: Use inherit to allow interactivity in yarn rw prisma

### LINKED ISSUE #1786: (critical bug v0.25 canary) `rw prisma` append and prepend content is blocking interactive and throwing error
@dac09 @dthyresson @peterp (Note: DT and I just worked through what's going on here).

## Problem
Using `0.25.1-canary.2`, which includes https://github.com/redwoodjs/redwood/pull/1785, interactive Prisma commands throw an error.

--> So a user **cannot** run interactive Prisma commands like `migrate dev`, `reset`, etc.

To reproduce:
- `rw upgrade -t canary`
- `rw prisma migrate reset` or `... migrate dev` if you don't have existing migrations

## Diagnosis
I believe the issue is actually with the _prepended_ content that displays the full CLI command with flags being run. In the case of `rw prisma migrate reset`:

1. we prepend the line:
```bash
Running prisma cli: 
yarn prisma migrate reset --preview-feature --schema "/Users/price/Repos/tdp-tutorial-blog-test/api/db/schema.prisma"
```
2. which causes Prisma to throw 'cause "non-interactive":
```bash
Error: We detected that your environment is non-interactive. Running this command in not supported in this context.
```
3. which also triggers our appended Redwood Tip, which will display on both `--help` and `error`:
```bash
...
🦺 Redwood CLI Tip    
```

Screen Shot 2021-02-12 at 4 50 05 PM

### PR DESCRIPTION
**Pull request by dac09**
Fixes #1786
**1. Allows interactivity when using commands like `yarn rw prisma migrate reset`**
Tape Preview

**2. Only show tip in help, or if prisma has yarn prisma in its output**
The downside:  if you run the wrong command, redwood tip won't show.
The upside: fail fast, and removes confusion where the tip isn't relevant, if you're running `yarn rw prisma migrate dev` and it fails, it won't show the tip (where its not relevant anyway)

### CODE REVIEW

File: packages/cli/src/commands/prisma.ts [hunk 1]
```diff
@@ -100,16 +97,11 @@ export const builder = async (yargs: Argv) => {
     // So we can check for yarn prisma in the output
     const { stdout } = await prismaCommand
 
-    // Show prisma cli output
-    // console.log(stdout)
-
-    if (hasHelpFlag || stdout.match('yarn prisma')) {
+    if (hasHelpFlag || stdout?.match('yarn prisma')) {
```
Comment (peterp) [inline packages/cli/src/commands/prisma.ts:100]: I don't really understand the second condition here? We're not running prisma via yarn, so is it checking for something else?

Comment (dac09) [reply packages/cli/src/commands/prisma.ts:100]: It's checking the output from the prisma cli, because the cli sometimes says stuff like "generated xxx, now run yarn prisma to yyy"

Comment (peterp) [reply packages/cli/src/commands/prisma.ts:100]: I actually see that the Prisma CLI always outputs something like this right at the top:
```
$ yarn rw prisma generate

Running prisma cli:
yarn prisma generate --schema "/private/var/folders/jj/brzmsc2562zbwgzwbnjdnqp80000gn/T/redwood.dQPMMURv/api/db/schema.prisma"
```

So, shouldn't this be showing the box on every command? 🤔

Comment (dac09) [reply packages/cli/src/commands/prisma.ts:100]: So that actually comes from our cli at this line https://github.com/redwoodjs/redwood/blob/2a1b4c6495a4933e5e2c5fd46d2e4e292011c57f/packages/cli/src/commands/prisma.ts#L77. That's why I do a check of the stdout from the prisma cli's output specifically

Comment (peterp) [reply packages/cli/src/commands/prisma.ts:100]: lol, wtf! I swear searched for this in our code before writing this comment... Could we change that up to read "Running Prisma CLI"

Comment (peterp) [reply packages/cli/src/commands/prisma.ts:100]: Hmpf. I'm trying to find the commands that ask you to do this, is it when you save a migration?

Comment (peterp) [reply packages/cli/src/commands/prisma.ts:100]: Anyway, don't want to bike-shed here too much. I approve this PR, but I would love it if you could document which commands would cause this trigger.

It might be that in future releases of Prisma they may not trigger this anymore, and we'll have this code lying around for no reason. It may also be easier to check the sequence of commands rather than the output.

**Review by peterp — CHANGES_REQUESTED** [review]
Please add a comment for the commands that would trigger the warning message to be displayed.

File: packages/cli/src/commands/prisma.ts (hunk 1 above)
Comment (dac09) [reply packages/cli/src/commands/prisma.ts:100]: Here's one `prisma introspect` -> https://s.tape.sh/7UcUY1t8 But I've seen it elsewhere (maybe migrate --create-only?)

Comment (dac09) [reply packages/cli/src/commands/prisma.ts:100]: The original PR actually has more in the description btw https://github.com/redwoodjs/redwood/pull/1772

Comment (peterp) [reply packages/cli/src/commands/prisma.ts:101]: 🆒 🆒 🆒 , I think documenting this is super important for future readers of the code

Comment (peterp) [reply packages/cli/src/commands/prisma.ts:101]: Since they don't have to wonder about what triggers it if they wanted to test it. They could just read a comment and figure, ah ok, I can test this by running `yarn rw prisma introspect`

**Review by peterp — APPROVED** [review]

**Comment by thedavidprice** [comment]
Thanks, gents! I'll jump into this in just a few minutes working toward a patch release today.

**Review by thedavidprice — APPROVED** [review]

**Comment by thedavidprice** [comment]
Ran through commands and cases locally. Double checked 'cause paranoid. Looking good!
