### PR TITLE
fix(auth): Implement automatic token refresh on supported providers

### LINKED ISSUE #1636: [Tracking] Validate token refresh issue across providers
This is a "meta issue" to track what auth providers have an issue, where the token is not automatically refreshed

Verified working

- [x] firebase
automagically refreshes the token, when getToken is called and the token is expired
- [x] supabase
needs client config. This needs to be configured by the user, not within RW.

Not verified:
- [ ] goTrue

As is:
- [x] magicLink

Needs fix:
- [x] netlify
- [x] auth0
Auth) requires user configuration. Added to various docs
- [x] azureActiveDirectory
Needs fix, see comment https://github.com/redwoodjs/redwood/issues/1636#issuecomment-768240131

Related to: #1627, #1576, #1608, #927, #738

--- 
### Help needed with:
a) Working out if this issue exists in each of the providers above
b) Comment on this issue if you find a unticked provider with their default expiry times
c) Working out if the auth client needs any extra code  or configuration in the `packages/src/authClients` to refresh its token automatically when `getToken` is called, or if it is handled internally by the authClient (such as firebase)

--- 
### How to reproduce
- Log into your RW app
- Wait for access token to expire (this will vary, based on your provider)
- Navigate to another page that needs auth to fetch data

`Very important!` You won't notice the issue if you refresh the page, but  its decent way of validating if the token refresh is handled for us. If you refresh and find that you got logged out, it is an indication that the client probably does not auto refresh the accessToken.

### PR DESCRIPTION
**Pull request by dac09**
Closes #1636

## What does it do?
Adds changes for two main cases:

a) Users are able to see errors in dev, if their access tokens expire
b) Changes auth clients to support automatically refreshing tokens (where available)

This PR was tested with the polling changes to auth playground: https://github.com/redwoodjs/playground-auth/

Todo:
- [x] Bump supabase js client in auth setup to minimum 1.9.0 if required
- [x] Change code in dev to atleast validate expiry so these errors get caught in development
- [x] Validate and fix the outstanding ones in #1636

---
Coauthored with @dthyresson 
Please address all bugs, critical feedback to DT.

### CODE REVIEW

File: packages/api/src/auth/decoders/auth0.ts [hunk 1]
```diff
@@ -33,44 +33,33 @@ export const verifyAuth0Token = (
       )
     }
 
-    if (
```
Comment (dac09) [inline packages/api/src/auth/decoders/auth0.ts:36]: @peterp we thought it best to maintain the same behaviour between dev and production for token validation. If there wasn't another reason you had it this way, are you happy with this change?

**Comment by dac09** [comment]
Confirmed fixed on:

- [x] netlify
- [x] supabase (no fix apart from upgrade)
- [x] auth0 (needs docs + config in userland)
- [x] firebase (was already working)

- [ ]  Azure/Microsoft does a redirect to login. Not too bad, but maybe one for @jeliasson to look into!

File: packages/auth/src/authClients/netlify.ts [hunk 2]
```diff
@@ -41,6 +41,9 @@ export const netlify = (client: NetlifyIdentity): AuthClient => {
       })
     },
     getToken: async () => {
+      // The client refresh function only actually refreshes token
+      // when it's been expired. Don't panic
+      client.refresh()
```
Comment (dac09) [inline packages/auth/src/authClients/netlify.ts:46]: Need to add an await here

**Review by dthyresson — CHANGES_REQUESTED** [review]
@dac09 I think we should revert the auth0 decoder so that API calls to Auth0 are not made in test -- and likely not in dev.

**Comment by dthyresson** [comment]
Have updated auth0 setup to include the information needed to setup refresh tokens.

Will also include this documentation in redwoodjs.com

File: packages/api/src/auth/decoders/auth0.ts (hunk 1 above)
Comment (dac09) [reply packages/api/src/auth/decoders/auth0.ts:36]: For test: yeah we can keep it there I guess. Would you expect jest to run an actual test calling this? I would imagine these decoders would be mocked (but I may be wrong).

But for dev, we should atleast do what we're doing on netlify, so the expirng tokens are a  _visible_ problem to the user, so they can fix.

File: packages/cli/src/commands/setup/auth/providers/auth0.js [hunk 3]
```diff
@@ -5,12 +5,27 @@ export const config = {
...
   client_id: process.env.AUTH0_CLIENT_ID,
   redirect_uri: process.env.AUTH0_REDIRECT_URI,
+
   // ** NOTE ** Storing tokens in browser local storage provides persistence across page refreshes and browser tabs.
   // However, if an attacker can achieve running JavaScript in the SPA using a cross-site scripting (XSS) attack,
   // they can retrieve the tokens stored in local storage.
   // https://auth0.com/docs/libraries/auth0-spa-js#change-storage-options
   cacheLocation: 'localstorage',
   audience: process.env.AUTH0_AUDIENCE,
+
```
Comment (dac09) [inline packages/cli/src/commands/setup/auth/providers/auth0.js:15]: Could we make this a little less verbose DT? Large comment blocks like this can seem daunting right after. Perhaps just a the `@MARK` and the link to refresh token rotation doc

`useRefreshTokens: true` should also be commented out by default, as that's the default on Auth0 server side too

Comment (dthyresson) [reply packages/cli/src/commands/setup/auth/providers/auth0.js:15]: I could put the info in the setup epilogue?

File: packages/api/src/auth/decoders/auth0.ts (hunk 1 above)
Comment (dthyresson) [reply packages/api/src/auth/decoders/auth0.ts:36]: Ok I will leave as is then.

**Review by dthyresson — APPROVED** [review]
I made this comment less verbose and added the content to the setup command epilogue output.

The info is also a part of the authentications docs:

See: https://github.com/redwoodjs/redwoodjs.com/pull/669

File: packages/api/src/auth/decoders/auth0.ts (hunk 1 above)
Comment (dac09) [reply packages/api/src/auth/decoders/auth0.ts:36]: @peterp, just need the 👍 from you :)
