### PR TITLE
fix(web): Fix importing .ts/.tsx files in web with directory-named-import plugin

### LINKED ISSUE #1214: Directory named babel plugin problems not working for `.tsx` files.

### LINKED ISSUE #1290: Unable to import ts/tsx components using short import path | v0.19.2
When trying to import a component without the absolute import path, error from webpack
```
Module not found: Can't resolve '../../components/AddTodo' in '/Users/xxx/Experiments/rw-example-todo/web/src/pages/HomePage'
```
Reproduced in example todo app, by renaming AddTodo.js to AddTodo.tsx. Also seeing the same issue on our app.

I suspect the issue may have been introduced here: https://github.com/redwoodjs/redwood/pull/1102/files

---

### Work around for now
Instead of importing the file like this:
```
import AddTodo from 'src/components/AddTodo'
```
can be imported like this
```
import AddTodo from '../../components/AddTodo/AddTodo'
```
Ugly I know!

---

RW Version: 0.19.2

### PR DESCRIPTION
**Pull request by dac09**
As title :)

Resolves #1290 
Resolves #1214

### todo

- [x] Add another test for typescript imports
- [x] Make sure it prefers index.{js/ts} over module name

### CODE REVIEW

File: packages/core/src/babelPlugins/babel-plugin-redwood-directory-named-import.ts [hunk 1]
```diff
@@ -9,7 +10,16 @@ const getNewPath = (value: string, filename: string) => {
   const newImportPath = [dirname, basename, basename].join('/')
 
   try {
```
Comment (peterp) [inline packages/core/src/babelPlugins/babel-plugin-redwood-directory-named-import.ts:12]: Since `resolveFile` returns null when the path isn't found, I think we can remove the try/catch blocks.
```suggestion

return resolveFile(
      path.join(path.dirname(filename), newImportPath)
    )
```

Comment (dac09) [reply packages/core/src/babelPlugins/babel-plugin-redwood-directory-named-import.ts:12]: 👍

**Comment by dac09** [comment]
Note: there is one failing test ```  // // Gives preferences to `index.*```` I'll fix this after lunch!

**Comment by peterp** [comment]
Oh windows!

**Comment by peterp** [comment]
I think @Tobbe contributed an utility called `poxisPath` in @redwoodjs/internal

**Comment by dac09** [comment]
> I think @Tobbe contributed an utility called `poxisPath` in @redwoodjs/internal

Giving that a go now 👍

**Comment by dac09** [comment]
@peterp ready for review. Finally got them windows paths! ✅

File: packages/core/src/babelPlugins/babel-plugin-redwood-directory-named-import.ts [hunk 2]
```diff
@@ -35,7 +43,7 @@ export default function ({ types: t }: { types: typeof types }): PluginObj {
 
         const newPath = getNewPath(value, <string>filename)
         if (!newPath) return
-        const newSource = t.stringLiteral(value.replace(value, newPath))
+        const newSource = t.stringLiteral(ensurePosixPath(newPath))
```
Comment (Tobbe) [inline packages/core/src/babelPlugins/babel-plugin-redwood-directory-named-import.ts:46]: <3

File: packages/core/src/babelPlugins/__tests__/babel-plugin-redwood-directory-named-imports.ts [hunk 3]
```diff
@@ -1,45 +1,53 @@
...
+const POSIX_DIRNAME = ensurePosixPath(__dirname)
+
 const testCases = [
-  // Directory named exports
+  // Directory named imports
   {
     input: 'import pew from "./__fixtures__/directory-named-imports/Module"',
-    output:
-      'import pew from "./__fixtures__/directory-named-imports/Module/Module"',
+    output: `import pew from "${POSIX_DIRNAME}/__fixtures__/directory-named-imports/Module/Module.js";`,
```
Comment (peterp) [inline packages/core/src/babelPlugins/__tests__/babel-plugin-redwood-directory-named-imports.ts:13]: Had a thought. Something feels off here, because imports in NodeJS are always in unix style. I guess it's because of the way that we get the absolute paths.

**Review by peterp — APPROVED** [review]

File: packages/core/src/babelPlugins/__tests__/babel-plugin-redwood-directory-named-imports.ts (hunk 3 above)
Comment (peterp) [reply packages/core/src/babelPlugins/__tests__/babel-plugin-redwood-directory-named-imports.ts:13]: Not exactly happy with this. There's nothing actionable, just thought I would mention it.

**Comment by peterp** [comment]
THanks <3!
