### PR TITLE
Fix Prisma Client error when running dev server w/out DB

### LINKED ISSUE #483: Check for existence of `api` directory when running `dev` and skip `api` and `db` tasks if it doesn't exist
For those that only want to deploy the web site, they should be able to delete `/api` completely and still be able to run `yarn rw dev` locally. Right now the `api` and `db` tasks raise all kinds of errors.

### PR DESCRIPTION
**Pull request by thedavidprice**
Fixes #483

By default, the Prisma Client would always run when using `yarn rw dev`. In the case of running `yarn rw dev --app web`, this would cause an error. This adds a check before running Prisma Client requiring both 1) the CLI command option including 'db' and 2) API directory existing.

Given that this command has 3 options, which can be used independently, I’m not sure if #490 was the best way forward -- the command `yarn rw dev web` would have started the web dev server only. The Prisma Client error would have still been an issue, however. Note: I did leave the api/ directory checks and also added it to the Prisma Client startup.

Any combination of commands or an individual command will now work, e.g. `yarn rw dev api web` will run the api and web servers without error. 

@peterp I think it's fine as is, but it's not clear to me why 'db' exists as a separate option from 'api'. (And 'db' is a bit of a misnomer since it's running `prisma generate`.)  But I guess if the two were combined, it wouldn't be possible for someone to swap the DB client in their own App, correct?

@cannikin for https://github.com/redwoodjs/redwoodjs.com/issues/125 you might want to use the `yarn rw dev --app web` command. (Note: --app not required.) Or if you want to delete the API directory and just run `yarn rw dev`, I'd suggest you still explain what the command is doing behind the scenes -- they can optionally choose which dev servers to run. fwiw...

### CODE REVIEW

File: packages/cli/src/commands/dev.js [hunk 1]
```diff
@@ -20,9 +20,11 @@ export const handler = async ({ app = ['db', 'api', 'web'] }) => {
...
   const WEB_DIR = path.join(BASE_DIR, 'web')
 
-  // Generate the Prisma client if it doesn't exist.
-  await generatePrismaClient({ verbose: false, force: false })
-
+  // Generate the Prisma client if it doesn't exist
+  // but only in case of db command option and API dir present
+  if (app.includes('db') && fs.existsSync(API_DIR)) {
+    await generatePrismaClient({ verbose: false, force: false })
+  }
```
Comment (peterp) [inline packages/cli/src/commands/dev.js:27]: This was originally added because the `api` dev server couldn't launch unless the database client was generated. It _might_ be the case that that's no longer true, and then we can remove this.

The way to test would be to ensure that `node_modules/@prisma/client` isn't generated, or if it's the latest version then delete `node_modules/.prisma`

**Comment by thedavidprice** [comment]
@peterp I've removed `await generatePrismaClient`, which I think is the correct way forward as it separates running the API dev-server from dependency on Prisma (e.g. in the case of an App *not* using a DB).

## Current Behavior
If a DB is being used and the file `graphql.js` implements Prisma Client, an error may result when _only_ the API dev-server is run. This seems appropriate, however (see more below).

Without the Prisma Client implementation in `graphql.js`, there are no errors for any configuration of commands.

### with import { db }
- if `yarn prisma generate` has not been run (therefore the Prisma Client does not exist) and
- if `api/src/functions/graphql.js` _includes_ `import { db } from 'src/lib/db'` 

then
- `yarn rw dev api` will **throw an Error** due to Prisma Client missing
- `yarn rw dev db api` runs correctly because `db` command generates Prisma Client
- `yarn rw dev web` runs correctly because no API
- `yarn rw dev ` runs correctly because `db` command generates Prisma Client

### without import { db }
- if `yarn prisma generate` has not been run (therefore the Prisma Client does not exist) andand
- if `import { db } from 'src/lib/db'` is _removed_ from `api/src/functions/graphql.js` (because there is no DB)

then everything runs correctly.

**Comment by peterp** [comment]
> I've removed await generatePrismaClient, which I think is the correct way forward as it separates running the API dev-server from dependency on Prisma (e.g. in the case of an App not using a DB).

The reason why it's separated is because we cannot start the dev-server if the database client isn't generated because it would throw an unhandled exception.

Basically that code was added to enable this workflow:

```terminal
yarn create redwood-app path/to/app
cd path/to/app
yarn rw dev
```

If that's still possible then I think this can be removed, but I would love it if our golden path was the first consideration.

I think how you had it originally was fine, which was to only generate the database client if app included `api` (default).

**Comment by thedavidprice** [comment]
Yes, it runs correctly.

The tutorial commands:
```bash
yarn create redwood-app path/to/app
cd path/to/app
yarn rw dev
```

Successfully runs:

```bash
$ yarn rw dev
yarn run v1.22.4
$ /Users/price/Repos/xx-delete/node_modules/.bin/rw dev
$ /Users/price/Repos/xx-delete/node_modules/.bin/dev-server
$ /Users/price/Repos/xx-delete/node_modules/.bin/prisma generate --watch
$ /Users/price/Repos/xx-delete/node_modules/.bin/webpack-dev-server --config ../node_modules/@redwoodjs/core/config/webpack.development.js
19:27:31  db |
19:27:31  db | Watching... /Users/price/Repos/xx-delete/api/prisma/schema.prisma
19:27:31  db |
19:27:31  db | ✔ Generated Prisma Client to ./../node_modules/@prisma/client in 61ms
19:27:31  db |
19:27:31 web | ℹ ｢wds｣: Project is running at http://localhost:8910/
19:27:31 web | ℹ ｢wds｣: webpack output is served from /
19:27:31 web | ℹ ｢wds｣: Content not from webpack is served from /Users/price/Repos/xx-delete/web
19:27:31 web | ℹ ｢wds｣: 404s will fallback to /index.html
19:27:32 api | Listening on http://localhost:8911
19:27:32 api | Watching /Users/price/Repos/xx-delete/api
19:27:32 api |
19:27:32 api | Now serving
19:27:32 api |
19:27:32 api | ► http://localhost:8911/graphql/
```

Note there is no longer a `✔ Generating the Prisma client...` that runs prior to the db, web, and API commands.

**Comment by peterp** [comment]
Nice!

**Comment by jtoar** [comment]
I'm seeing this issue come up again with new apps:

```
yarn create redwood-app path/to/app
cd path/to/app
yarn rw dev
...
22:31:09 api | Running at 'http://localhost:8911'
22:31:09 api | Watching files in '/home/dominic/projects/redwood/redwoodblog/api/src/functions'
22:31:11 api | /home/dominic/projects/redwood/redwoodblog/node_modules/.prisma/client/index.js:3
22:31:11 api |     throw new Error(
22:31:11 api |     ^
22:31:11 api | 
22:31:11 api | Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
22:31:11 api | In case this error is unexpected for you, please report it in https://github.com/prisma/prisma-client-js/issues/390.
```

@thedavidprice @peterp Is this the case for either of you guys too?
