### PR TITLE
[Router] fixes `validatePath` duplicate params & reject spaces in routes

### LINKED ISSUE #382: [Router] Routes allow spaces but fail on them
The `/\{([^}]+)\}/g` regexp that's widely used in the router's implementation allows spaces in param names and types, as well as before or after the colon.

However, the rest of the code is not prepared for spaces within the type names: trying to match the route `/posts/{id: Int}` will fail trying to look for a `" Int"` type within the known types...

Happy to open a PR to change that, however I'm wondering how you'd treat the issue:
- Disallow spaces in route params
- or be space-proof in route processing?

Personally, I'd vote for the former, as that'd make it easier to have a single way of doing things, and who wants a `/route/{my param: Int}` anyway?

### PR DESCRIPTION
**Pull request by olance**
Closes #382 

This PR makes `validatePath` throw an error when a route's provided path contains at least one space character.
It's only looking for `' '`; I figured other whitespace characters such as `'\t'`, `'\n'`, ... would make so little sense that it does not warrant "complicating" the code & tests with that.

Super easy to change if you'd rather reject everything though!

I also took the opportunity to fix the duplicate params detection, which was broken when only one of two duplicates used a type, and to refactor the router's utils tests a little 🙂 

**Question:** I intentionally added a test case that validates `'/users/{id}/photos/{photo_id}?format=jpg&w=400&h=400'` as a valid route.
I don't see why not, but I wanted to make sure we actually allow query strings in routes paths?

### CODE REVIEW

**Comment by olance** [comment]
@thedavidprice not sure why checks are run twice?

**Comment by thedavidprice** [comment]
Thanks. I see it and have a theory re: GH Action matrix build bug. Hoping to resolve soon.

**Comment by thedavidprice** [comment]
FYI: we’ve added a CI runner for Windows and changed PR settings to require checks to pass before merging. Pulling in changes from master should resolve current warnings.

**Comment by olance** [comment]
@thedavidprice @peterp this is ready to be reviewed 🙂

File: packages/router/src/util.js [hunk 1]
```diff
@@ -128,18 +128,23 @@ const parseSearch = (search) => {
...
   // Check for duplicate named params.
   const matches = path.matchAll(/\{([^}]+)\}/g)
   let memo = {}
   for (const match of matches) {
-    const param = match[0]
+    // Extract the param's name to make sure there aren't any duplicates
+    const param = match[1].split(':')[0]
     if (memo[param]) {
-      throw new Error('Route path contains duplicate parameter: "' + path + '"')
+      throw new Error(`Route path contains duplicate parameter: "${path}"`)
```
Comment (peterp) [inline packages/router/src/util.js:145]: Could we make a test for this exception? `expect().toThrow()`

Comment (peterp) [reply packages/router/src/util.js:145]: Sorry, I saw you have that!
