### PR TITLE
fix prisma version field resolver not working

### LINKED ISSUE #1439: "TypeError: Cannot read property 'client' of undefined" in latest canary
Hi all, 

from `0.20.1-canary.17` upwards getting locally ...

```
TypeError: Cannot read property 'client' of undefined
api |
api |
api | 1 redwood
api |  [redacted]/node_modules/@redwoodjs/api/dist/makeMergedSchema/rootSchema.js:55
api |
api | 2 field.resolve
api |  [redacted]/node_modules/graphql-extensions/src/index.ts:274
api |
api | 3 field.resolve
api |   [redacted]/node_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:103
api |
api | 4 resolveFieldValueOrError
api |   [redacted]/node_modules/graphql/execution/execute.js:502
api |
api | 5 resolveField
api |  [redacted]/node_modules/graphql/execution/execute.js:460
api |
api | 6 executeFields
api |   [redacted]/node_modules/graphql/execution/execute.js:297
api |
api | 7 executeOperation
api |  [redacted]/node_modules/graphql/execution/execute.js:241
api |
api | 8 executeImpl
api |   [redacted]/node_modules/graphql/execution/execute.js:119
api |
api | 9 Object.execute
api |   [redacted]/node_modules/graphql/execution/execute.js:63
api |
api | 10 anonymous
api |   [redacted]/node_modules/apollo-server-core/src/requestPipeline.ts:545
api |

```

### PR DESCRIPTION
**Pull request by AntonioMeireles**
fixes typo introduced [here](https://github.com/redwoodjs/redwood/commit/0f1a378829fb280e7a2e89f914ce69baf5130f44) which seems to be breaking latest canary revs. 

All the best, 

António

### CODE REVIEW

File: packages/api/src/makeMergedSchema/rootSchema.ts [hunk 1]
```diff
@@ -53,7 +53,7 @@ export const resolvers: Resolvers = {
   Query: {
     redwood: () => ({
       version: apiPackageJson.version,
-      prismaVersion: PrismaClient.prismaVersion.client,
+      prismaVersion: PrismaClient.prismaVersion,
```
Comment (peterp) [inline packages/api/src/makeMergedSchema/rootSchema.ts:56]: Hmmmm... Maybe it's best to make this a resolver, can you wrap this in a function?
```suggestion
      prismaVersion: () => PrismaClient.prismaVersion,
```

**Comment by AntonioMeireles** [comment]
@peterp - squashed  to reduce noise.

**Comment by peterp** [comment]
Thanks Antonio, do you know if this returns the version when you try it?

**Review by peterp — APPROVED** [review]

**Comment by AntonioMeireles** [comment]
> Thanks Antonio, do you know if this returns the version when you try it?

well, actually didn't check (just identified breaking commit and got rid of the fatal breakage on the fly). Will do in a bit, after lunch break and an ... haircut.

**Comment by peterp** [comment]
Oh lol... ok, I'm also getting a haircut. I wish you luck and hope it turns out stylish.
