### PR TITLE
Checking jest config web api

### LINKED ISSUE #907: Running yarn rw test should automatically generate jest.config.js files for api and web if they're missing
**EDIT:** The original issue is solved by adding jest.config.js files. So, running `yarn rw test` should automatically generate jest.config.js files for api and web if they're missing.

Original issue: Tests [web] are failing to run because __REDWOOD__API_PROXY_PATH is not defined
```bash
yarn rw test web

Test suite failed to run

    ReferenceError: __REDWOOD__API_PROXY_PATH is not defined

    > 1 | import { render } from '@redwoodjs/testing'
        | ^
      2 | 
      3 | import { Header } from './Header'
      4 | 

      at Object.<anonymous> (../node_modules/@redwoodjs/web/dist/config.js:5:36)
      at Object.<anonymous> (../node_modules/@redwoodjs/web/dist/index.js:68:1)
      at Object.<anonymous> (../node_modules/@redwoodjs/testing/dist/MockProviders.js:15:12)
      at Object.<anonymous> (../node_modules/@redwoodjs/testing/dist/customRender.js:17:22)
      at Object.<anonymous> (../node_modules/@redwoodjs/testing/dist/index.js:78:21)
      at Object.<anonymous> (src/components/Header/Header.test.js:1:1)
`

```bash
yarn rw info

yarn run v1.22.4
$ /Users/terriskremer/Sites/kremer/kremerlibrary/node_modules/.bin/rw info

  System:
    OS: macOS Mojave 10.14.6
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.1 - /var/folders/s3/jyccmmxs11j893bfb92tt0900000gn/T/yarn--1596039261212-0.9150607551937429/node
    Yarn: 1.22.4 - /var/folders/s3/jyccmmxs11j893bfb92tt0900000gn/T/yarn--1596039261212-0.9150607551937429/yarn
  Databases:
    SQLite: 3.24.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 74.0
    Safari: 13.1.2
  npmPackages:
    @redwoodjs/core: ^0.14.0 => 0.14.0

### PR DESCRIPTION
**Pull request by josemasar**
Fixes #907 

### Background
Running 'yarn rw test' would fail **without giving an indication to the user** when`jest.config.js` files are missing in '/web' or '/api' sides. 

### Proposed solution
This PR is intending to check if the Jest config files exists in each of the sides and when they miss, the user will get an error indicating to run a codemod to resolve the problem. 

### Tag a friend mantainer 
@thedavidprice

### CODE REVIEW

**Comment by josemasar** [comment]
@thedavidprice, these are the console error messages showing when the Jest config file is missing. In addition, it´s throwing an error to prevent that the tests are running, so that, the user can read  the error messages (and not  logs from a bunch of tests failing). I also proved that by running the codemod, it´s restoring/creating the appropiate config file in api/web. 

yarn rw test

File: packages/cli/src/commands/test.js [hunk 1]
```diff
@@ -134,6 +137,49 @@ export const handler = async ({
...
+          c.error(
+            'Run codemod `npx @redwoodjs/codemods@latest update-jest-config`.'
+          )
+        )
+        console.error(
+          c.error(
+            'This command will automatically update your project to the latest Jest config.'
+          )
+        )
+        throw new Error('Error: Jest config file not found in api side')
```
Comment (thedavidprice) [inline packages/cli/src/commands/test.js:156]: I think this is a good opportunity for DRY programming — create a function and pass in the side. Also, you might just have one `console.error` and use line breaks `\n` (template literal should add line breaks if you separate onto lines, I believe).

I would definitely add line break before and after the console error. Visually it helps to make the output separate. And you can consolidate into two lines with something like this:
```
Error: Jest config file not found `api/jest.config.js`
To add this file, run `npx @redwoodjs/codemods update-jest-config`
```

**Review by thedavidprice — CHANGES_REQUESTED** [review]
Looking good! Functionally fine as is. But some recommendations to improve code and console error output.

Open to discussion as needed.

**Comment by josemasar** [comment]
@thedavidprice , I refactored into a function and included the line breaks. After the changes, it´s fully working. 
yarn rw test new

File: packages/cli/src/commands/test.js [hunk 2]
```diff
@@ -27,6 +30,28 @@ function isInMercurialRepository() {
...
+function isJestConfigFile(sides) {
+  for (let side of sides) {
+    try {
+      if (sides.includes(side)) {
+        if (!fs.existsSync(path.join(side, 'jest.config.js'))) {
+          console.error(
+            c.error(
+              `Error: Jest config file not found ${side}/jest.config.js`,
+              '\n',
+              'To add this file, run `npx @redwoodjs/codemods update-jest-config`'
```
Comment (thedavidprice) [inline packages/cli/src/commands/test.js:42]:
```suggestion
              `\nError: Missing Jest config file ${side}/jest.config.js
              To add this file, run 'npx @redwoodjs/codemods update-jest-config'\n`
```

File: packages/cli/src/commands/test.js [hunk 3]
```diff
@@ -27,6 +30,27 @@ function isInMercurialRepository() {
...
 
+function isJestConfigFile(sides) {
+  for (let side of sides) {
+    try {
+      if (sides.includes(side)) {
+        if (!fs.existsSync(path.join(side, 'jest.config.js'))) {
+          console.error(
+            c.error(
+              `\nError: Missing Jest config file ${side}/jest.config.js
+              To add this file, run 'npx @redwoodjs/codemods update-jest-config'\n`
```
Comment (thedavidprice) [inline packages/cli/src/commands/test.js:41]:
```suggestion
            `\nError: Missing Jest config file ${side}/jest.config.js` + 
            '\nTo add this file, run `npx @redwoodjs/codemods update-jest-config`\n'
```

Build messed up formatting. Fixed.

**Review by thedavidprice — CHANGES_REQUESTED** [review]
@josemasar Code looks great! I formatted the output (minor). Well done.

So looks like you have a legitimate CI error for `yarn test` being thrown here, which you'll need to resolve:
https://github.com/redwoodjs/redwood/runs/5324955239?check_suite_focus=true#step:11:1059

Check out the specific test here:
https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/__tests__/test.test.js

And the additionally utilities, fixtures, etc. being used from here:
https://github.com/redwoodjs/redwood/tree/main/packages/cli/src/lib

What you'll need to do is create a mock for the config files (I'd just do it within the test itself, mocking paths for fs.existsSync). I don't think you need a test confirming the command fails if the files aren't present, but you're welcome to try if you'd like!

File: packages/cli/src/commands/__tests__/test.test.js [hunk 4]
```diff
@@ -19,7 +22,19 @@ jest.mock('@redwoodjs/structure', () => {
   }
 })
 
+jest.mock('fs')
+
+const MOCK_CONFIG_FILES = {
+  'api/jest.config.js': 'api jest config file',
+  'web/jest.config.js': 'web jest config file',
+}
```
Comment (thedavidprice) [inline packages/cli/src/commands/__tests__/test.test.js:30]: @Tobbe This is failing on Windows ('cause posix-only paths). Could you help guide @josemasar in the best direction toward the helpers we use to mock file system cross platform? Thanks in advance!

**Comment by Tobbe** [comment]
I'm away most of this weekend. Will reply as soon as I can

File: packages/cli/src/commands/__tests__/test.test.js (hunk 4 above)
Comment (thedavidprice) [reply packages/cli/src/commands/__tests__/test.test.js:30]: @josemasar Since Tobbe won't be able to review until next week, if you have the time to look through CLI tests in general to see how cross-platform fixtures are handled I bet you'll find a path forward. For example, check out the `ensurePosixPath` export from the Internal package (I'm just not sure if this will work the same for fixtures).

**Comment by josemasar** [comment]
@thedavidprice, I found a very good example in `serve.test.js`. 

Now all checks have passed. 

Have a great weekend 😉

File: packages/cli/src/commands/__tests__/test.test.js [hunk 5]
```diff
@@ -19,6 +20,13 @@ jest.mock('@redwoodjs/structure', () => {
   }
 })
 
+jest.mock('fs', () => {
+  return {
+    ...jest.requireActual('fs'),
+    existsSync: () => true,
+  }
+})
+
```
Comment (thedavidprice) [inline packages/cli/src/commands/__tests__/test.test.js:29]: @josemasar I do think this is an ok choice here. Because the new code is a functional catch for misconfiguration, it's not necessary to add a test to avoid regression (any conceivable changes to template config will be test enough). Effectively all that needs to be done is to make sure the tests can run without the new code interferring.

If there were previous uses of existsSync, we'd want to be more precise. Theoretically someone could add code that uses existsSync and the tests result in a false positive. But I'll just add a comment here to state why this is added in the first place.

File: packages/cli/src/commands/__tests__/test.test.js [hunk 6]
```diff
@@ -19,6 +20,13 @@ jest.mock('@redwoodjs/structure', () => {
   }
 })
 
+jest.mock('fs', () => {
```
Comment (thedavidprice) [inline packages/cli/src/commands/__tests__/test.test.js:23]:
```suggestion
// Before rw tests run, api/ and web/ `jest.config.js` is confirmed via existsSync()
jest.mock('fs', () => {
```
