### PR TITLE
Fix telemetry showing Node version for Yarn and npm

### LINKED ISSUE #4290: Data for npm and Yarn version is duplicate of Node.js version (telemetry)
I am seeing identical telemetry values for `NodeVersion`, `NpmVersion`, and `YarnVersion`. 
Screen Shot 2022-01-28 at 9 39 15 AM

### PR DESCRIPTION
**Pull request by cannikin**
Closes #4290

### CODE REVIEW

File: packages/telemetry/src/sendTelemetry.ts [hunk 1]
```diff
@@ -82,8 +82,8 @@ const getInfo = async (presets = {}) => {
     osVersion: info.System?.OS?.split(' ')[1],
     shell: info.System?.Shell?.name,
     nodeVersion: info.Binaries?.Node?.version,
-    yarnVersion: info.Binaries?.Node?.version,
-    npmVersion: info.Binaries?.Node?.version,
```
Comment (thedavidprice) [inline packages/telemetry/src/sendTelemetry.ts:86]: Ha! Yep, that would do it 😆

**Review by thedavidprice — APPROVED** [review]
Confirmed it's now correct over here:
https://github.com/redwoodjs/redwood/runs/5010188352?check_suite_focus=true#step:12:36
