### PR TITLE
Fix lint breaking when deleting a side

### LINKED ISSUE #2016: Linting breaks when disabling side
When api is disabled linting no longer works.
image

### PR DESCRIPTION
**Pull request by magicjuju**
Fixes #2016

### CODE REVIEW

File: packages/cli/src/commands/lint.js [hunk 1]
```diff
@@ -21,8 +23,23 @@ export const builder = (yargs) => {
...
+
+  if (fix) {
+    options.push('--fix')
+  }
+  if (webExists) {
+    options.push('web/src')
+  }
+  if (apiExists) {
+    options.push('api/src')
+  }
```
Comment (peterp) [inline packages/cli/src/commands/lint.js:39]: Thanks for this:

another way of writing this would be:
```suggestion
  [
     fix && '--fix',
     webExists && 'web/src',  
     apiExists && 'api/src',
  ].filter(Boolean)
```

Comment (magicjuju) [reply packages/cli/src/commands/lint.js]: Thanks for the feedback. I've made those changes.

File: packages/cli/src/commands/lint.js [hunk 2]
```diff
@@ -21,9 +23,19 @@ export const builder = (yargs) => {
...
+    'yarn eslint',
+    [fix && '--fix', webExists && 'web/src', apiExists && 'api/src'].filter(
+      Boolean
+    ),
+    {
+      cwd: paths.base,
+      shell: true,
+      stdio: 'inherit',
+    }
+  )
```
Comment (Tobbe) [inline packages/cli/src/commands/lint.js:40]:
```suggestion
  execa(
    'yarn eslint',
    [
      fix && '--fix',
      fs.existsSync(getPaths().web.src) && 'web/src',
      fs.existsSync(getPaths().api.src) && 'api/src',
    ].filter(Boolean),
    {
      cwd: getPaths().base,
      shell: true,
      stdio: 'inherit',
    }
  )
```

This is silly, but because doing it this way makes prettier keep the array elements on separate lines, I like this more.

Comment (magicjuju) [reply packages/cli/src/commands/lint.js]: No problemo

**Review by Tobbe — APPROVED** [review]
