### PR TITLE
Fixes setting Prisma Version in root redwood schema

### LINKED ISSUE #1439: "TypeError: Cannot read property 'client' of undefined" in latest canary
Hi all, 

from `0.20.1-canary.17` upwards getting locally ...

```
TypeError: Cannot read property 'client' of undefined
api |
api |
api | 1 redwood
api |  [redacted]/node_modules/@redwoodjs/api/dist/makeMergedSchema/rootSchema.js:55
api |
api | 2 field.resolve
api |  [redacted]/node_modules/graphql-extensions/src/index.ts:274
api |
api | 3 field.resolve
api |   [redacted]/node_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:103
api |
api | 4 resolveFieldValueOrError
api |   [redacted]/node_modules/graphql/execution/execute.js:502
api |
api | 5 resolveField
api |  [redacted]/node_modules/graphql/execution/execute.js:460
api |
api | 6 executeFields
api |   [redacted]/node_modules/graphql/execution/execute.js:297
api |
api | 7 executeOperation
api |  [redacted]/node_modules/graphql/execution/execute.js:241
api |
api | 8 executeImpl
api |   [redacted]/node_modules/graphql/execution/execute.js:119
api |
api | 9 Object.execute
api |   [redacted]/node_modules/graphql/execution/execute.js:63
api |
api | 10 anonymous
api |   [redacted]/node_modules/apollo-server-core/src/requestPipeline.ts:545
api |

```

### PR DESCRIPTION
**Pull request by AntonioMeireles**
actually fetch and consume prismaVersion the right way

#1495 solved the crash but didn't solve the root issue which was to actually have #1395
working as intended. (my bad for not testing enough :( ).

this one fixes it (famous last words).

All the best, and sorry for the noise

### CODE REVIEW

**Comment by peterp** [comment]
no worries, my bad for just merging. someday we'll have tests for this 👍

**Comment by AntonioMeireles** [comment]
fix still failing . on barber shop now, will try to finally get it right
later today

thnxs for your patience

**Comment by AntonioMeireles** [comment]
@peterp 

the good news is that i 'think' that patch is right, the bad news is that i don't get why tests are failing (not too familiar with yarn / current build machinery). can you take plz a look / give an hint ?

**Comment by AntonioMeireles** [comment]
@peterp 

FWIW, tests pass now; my ts foo is not deep enough to fully understand why things had to be the way they ended to be (require instead of import).

**Comment by jvanbaarsen** [comment]
@AntonioMeireles Thanks for fixing this :-) When I wrote this feature/change I tested it locally, and it was actually returning the Apollo version. Why was your original change needed? (That way I know what I overlooked)

**Comment by AntonioMeireles** [comment]
> @AntonioMeireles Thanks for fixing this :-) When I wrote this feature/change I tested it locally, and it was actually returning the Apollo version. Why was your original change needed? (That way I know what I overlooked)

(thanks me for you adding key new functionality :-) sorry lag)

let's see if i get the timeline right ...

a) the code example you had [here](https://github.com/redwoodjs/redwood/issues/1395#issue-728058526) was right.
b) *but* that wasn't the way you did it in the [actual PR](https://github.com/redwoodjs/redwood/pull/1425/files). (note the `import` vs `require`). that code built *but*  at runtime induced breakage (`"TypeError: Cannot read property 'client' of undefined"`) as soon as it was merged in the following canary builds. 
c) meanwhile in my side, as  i only wanted to get runtime to not crash i,  ended providing a short-sighted fix which when merged solved the runtime issue but *not* get the desired functionality to actually work. 
d) the current patch ideally fixes all this. (do note the original `import { PrismaClient } from '@prisma/client'` vs the final `const { prismaVersion } = require('@prisma/client')` which incidentally is exactly what was supposed to be in first place (see the snippet you posted in the original issue ( vd a) ) 

Hope this helps, 

and a great weekend!

**Comment by jvanbaarsen** [comment]
@AntonioMeireles Hm, still weird that I actually got a proper apolloVersion in my local test. But maybe I overlooked something :-)

File: packages/api/src/makeMergedSchema/rootSchema.ts [hunk 1]
```diff
@@ -1,6 +1,6 @@
 /* eslint-disable @typescript-eslint/ban-ts-comment */
 import type { GlobalContext } from 'src/globalContext'
-import { PrismaClient } from '@prisma/client'
+const { prismaVersion } = require('@prisma/client')
```
Comment (dthyresson) [inline packages/api/src/makeMergedSchema/rootSchema.ts:3]: Is there a reason why this line is not:

`import { prismaVersion } =  from '@prisma/client'`

?

Comment (Tobbe) [reply packages/api/src/makeMergedSchema/rootSchema.ts:3]: I think @AntonioMeireles already tried that over here: https://github.com/AntonioMeireles/redwood/commit/3283d28b8d03223e6f6dfaacc8d4fa76d271bc2b

Comment (Tobbe) [reply packages/api/src/makeMergedSchema/rootSchema.ts:3]: Not sure why it didn't work though...

Comment (jvanbaarsen) [reply packages/api/src/makeMergedSchema/rootSchema.ts:3]: Yeah that doesn't work somehow. That was the reason I originally imported the `prismaClient` and fetched the version from there.

Comment (AntonioMeireles) [reply packages/api/src/makeMergedSchema/rootSchema.ts:3]: yes... for reasons that i don't get it simply does not work as the typescript compiler doesn't like it... 

build busts with ... 
```
6:27:15 PM] Building project '/Users/am/hacks/homeWare/redwood/packages/api/tsconfig.json'...

packages/api/src/makeMergedSchema/rootSchema.ts:4:1 - error TS6133: 'PrismaClient' is declared but its value is never read.

4 import { PrismaClient } from '@prisma/client'
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

packages/api/src/makeMergedSchema/rootSchema.ts:57:28 - error TS2304: Cannot find name 'prismaVersion'.

57       prismaVersion: () => prismaVersion.client,
                              ~~~~~~~~~~~~~
```

with `const { prismaVersion } = require('@prisma/client')` it just builds.

Comment (AntonioMeireles) [reply packages/api/src/makeMergedSchema/rootSchema.ts:3]: frankly my ts foo is not deep enough to spot why this has to be this way .

Comment (dthyresson) [reply packages/api/src/makeMergedSchema/rootSchema.ts:3]: Does this

https://github.com/prisma/prisma-client-js/issues/573

help?

```
/**
 * Query Engine version: 4ff8379527ec7797e7bb5b55d374f82f5812a6f9
 * Prisma Client JS version: 2.0.0-alpha.913
 */
exports.version = {
  engine: "4ff8379527ec7797e7bb5b55d374f82f5812a6f9",
  client: "2.0.0-alpha.913"
}
```

Maybe

```
import { version} from '@prisma/client'

...

prismaVersion: () => version.client,

```

Comment (AntonioMeireles) [reply packages/api/src/makeMergedSchema/rootSchema.ts:3]: no. they renamed a bit later - https://github.com/prisma/prisma-client-js/commit/ce3e7effb2d0d3a865d0beafec78f73abddf89cf  (to `prismaVersion`)
It's  worth nothing that expected code to work *only* fails over typescript. as javascript it builds/runs nicely. when in typescript somehow the type machinery gets fooled.

Comment (AntonioMeireles) [reply packages/api/src/makeMergedSchema/rootSchema.ts:3]: (fixed above the commit where they actually `s/version/prismaVersion/`)

Comment (dthyresson) [reply packages/api/src/makeMergedSchema/rootSchema.ts:3]: > no. they renamed a bit later

🙄  oh did they? 

sometimes i refuse to give up. i tried!

Comment (peterp) [reply packages/api/src/makeMergedSchema/rootSchema.ts:3]: I think the reason why it probably didn't work could be because the client isn't generated. I think we should inline the entire `require` statement.

Comment (AntonioMeireles) [reply packages/api/src/makeMergedSchema/rootSchema.ts:3]: hang on, a bit. 

error snippet above was wrong. 
real error when trying to do things the expected way is ... 
```
6:47:40 PM] Building project '/Users/am/hacks/homeWare/redwood/packages/api/tsconfig.json'...

packages/api/src/makeMergedSchema/rootSchema.ts:4:10 - error TS2305: Module '"../../../../node_modules/@prisma/client"' has no exported member 'prismaVersion'.

4 import { prismaVersion } from '@prisma/client'
           ~~~~~~~~~~~~~

[6:47:44 PM] Project 'packages/api-server/tsconfig.json' is up to date because newest input 'packages/api-server/src/error.ts' is older than oldest output 'packages/api-server/dist/error.d.ts.map'


Found 1 error.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 
```

googling a bit i get https://github.com/prisma/prisma/issues/2584 which may or not be related ...
it references symlinks which rw workspaces abuse a lot . again ts / yarn not my core domain at all :-)

Comment (dthyresson) [reply packages/api/src/makeMergedSchema/rootSchema.ts:3]: As I was digging through

Comment (AntonioMeireles) [reply packages/api/src/makeMergedSchema/rootSchema.ts:3]: > I think the reason why it probably didn't work could be because the client isn't generated.

re-reading prisma/prisma#2584  it may be just that, yes!

Comment (Tobbe) [reply packages/api/src/makeMergedSchema/rootSchema.ts:3]: Yeah, looking at prisma client's index.d.ts for the rw framework project it's basically just 
```
export declare const PrismaClient: any
export declare type PrismaClient = any
```

But if you look at it in a RW project where the client has been generated index.d.ts has a lot more, like
```
/**
 * Prisma Client JS version: 2.9.0
 * Query Engine version: 369b3694b7edb869fad14827a33ad3f3f49bbc20
 */
export declare type PrismaVersion = {
  client: string
}

export declare const prismaVersion: PrismaVersion 
```
