### PR TITLE
GraphQL Codegen for generating gql types

### LINKED ISSUE #418: [RFC] Typed GraphQL
There is interest in making Redwood GraphQL operations type-safe. Since Redwood is full-stack, we can offer a much better integration with code-generators and React components than existing solutions. 

Core of my proposal is that type code generation and usage is invisible to the user.

### State of the art 
Currently using code generators such as Apollo or graphql-code-generator requires user to setup a watcher that watches graphql schema and existing query/mutation files, then it writes down resulting generated code. The second step is to import those generated types to make GraphQL operations type safe.

```ts
import { useQuery } from 'react-apollo';

import GetUserProfile from './GetUserProfile.graphql'

import { GetUserProfile as IGetUserProfile, GetUserProfileVariables } from './__generated__/GetUserProfile.ts';

const { data } = useQuery<IGetUserProfile, GetUserProfileVariables>(GetUserProfile);
```

oof! So much boilerplate and importing just to get that `data` typed properly. 

The [graphql-code-generator typescript-react-apollo](https://graphql-code-generator.com/docs/plugins/typescript-react-apollo) offers generating code that includes those imports so using the `GetUserProfile` query is as simple as following

```ts
import { useGetUserProfileQuery } from './__generated__'
```

This hook is strongly typed and the resulting `data` will have proper typing. 

The generated code is living alongside of the source code which makes code structure extremely polluted.

### Proposal 
The code generation should be done as part of Redwood dev server process and be completely invisible to the user. 

#### Put generated code in node_modules
Learning from Prisma, I think this generated code can go straight into `@redwood/web` so we can avoid team debates on "should we check in the generated code or not?"!!

All of generated code can live under `/types` directory 

#### Use TypeScript Namespaces 
This will allow access to deeper interfaces using `.` instead of typical bracket notation.

`GetBlogPosts.Success` looks better than `GetBlogPosts['Success']`

### Example
We can imagine generating a Cell for `BlogPosts` from the tutorial would look like:
 
```tsx

export const QUERY = gql`
  query GetBlogPosts {
    blogPosts {
      id
    }
  }
`
import { GetBlogPosts } from '@redwood/web/types';

export const Loading = () => <div>Loading...</div>

export const Empty = () => <div>Empty</div>

export const Failure: GetBlogPosts.Failure = ({ error }) => <div>Error: {error.message}</div>

export const Success: GetBlogPosts.Success = ({ blogPosts }) => {
  return JSON.stringify(blogPosts)
}
```

Notes about example
* Query is named. This helps the codegen generated better looking types. Query names must be unique to avoid name collision. 
* Only Success and Failure are typed. No reason to type Empty and Loading. However they better be `React.FC` type.
* Import is coming after definition of the QUERY. I think this is useful because it implies that types are result of query. This might break linting and we decide it is not worth it. 

### Implementation details

Work to do this requires changes in the core and default template. [Why the template is not in the monorepo?](https://github.com/redwoodjs/redwood/issues/419)

#### graphql-code-generator
We would probably require to write a custom plugin for graphql-code-generator tailored to Redwood use case. 

#### Possible challenges

* Renaming/Deleting queries: codegens are terrible at cleaning up after themselves 
* TypeScript Language server heavily caching node_modules types and editors not picking up newly generated types in the node_moduels. @nikolasburk and @imsuchanek did you have this problem in Prisma?

### PR DESCRIPTION
**Pull request by dac09**
## What does it do?

1. Adds command `yarn rw generate types` which will generate all autogenerated types (currently CurrentUser and graphql types)
2. Modifies `yarn rw dev` to also call above generator
3. Makes `QueryOperationResult` and `MutationOperationResult` overridable types so that when you bring your gql client, you can add your own types. (See packages/web/src/apollo/typeOverride.ts)

The generated types can be used like this:
```ts
// import generate type ->
import { PetQuery } from 'types/gql-types'
import type { CellSuccessProps, CellFailureProps } from '@redwoodjs/web'

export const QUERY = gql`
  query PetQuery {
    pets {
      id
    }
  }
`
// -> See type declaration here
export const Success = ({ pets }: CellSuccessProps<PetsQuery>) => {
```

You also get types from the Apollo client! (Overridable for other clients)

I realise that its unusal that `rw generate types --watch` has a watch flag, open to suggestions for a better way. I just thought generate was the best place to put this.

Uses graphql-codegen underneath.

### Outstanding tasks:
- [ ] ~Investigate using `makeMergeSchema` instead of the actual api server for generating types~
**Update:** Peter's cell mirrored types may generate the schema to a file, which we can reuse.
- [x] Remove generating types from build process elsewhere
- [x] Modify typescript generators for Cells to import types "optimistically"
- [x] Modify naming of scaffold queries to prevent conflicts in names (e.g. EditTaskQuery vs GetTaskQuery)
was already done in another PR
- [x] Also pass other props passed to the Cell components (`...queryRest`)
- [x] Handle plural cells and their types
- [x] Handle typescript templates for `.stories.tsx`, `.tests.tsx` and `.mocks.ts`

--- 
Closes  #418

### CODE REVIEW

File: packages/web/src/index.ts [hunk 1]
```diff
@@ -12,11 +12,12 @@ export {
   useMutation,
 } from './components/GraphQLHooksProvider'
 
-import { createCell } from './components/createCell'
-export { createCell }
-
-/** @deprecated `withCell` will be removed in v0.32.0, please use `createCell` instead. */
-export const withCell = createCell
```
Comment (dac09) [inline packages/web/src/index.ts:19]: Note that I've removed withCell

File: packages/cli/src/commands/generate/cell/__tests__/__snapshots__/cell.test.js.snap [hunk 2]
```diff
@@ -169,7 +169,7 @@ export const Success = ({ userProfile }) => {
 
 exports[`creates a cell mock with a camelCase word name 1`] = `
 "// Define your own mock data here:
-export const standard = (/* vars, { ctx, req } */) => ({
```
Comment (dac09) [inline packages/cli/src/commands/generate/cell/__tests__/__snapshots__/cell.test.js.snap:172]: I dunno why the snapshots do this weird thing. Its not actually doing this when we actually generate 🤷‍♂️

File: packages/cli/src/commands/generate/cell/__tests__/__snapshots__/cell.test.js.snap [hunk 3]
```diff
@@ -414,7 +416,7 @@ describe('UserProfileCell', () => {
 `;
 
 exports[`creates a cell test with a multi word name 1`] = `
-"import { render, screen } from '@redwoodjs/testing'
+"import { render } from '@redwoodjs/testing'
```
Comment (dac09) [inline packages/cli/src/commands/generate/cell/__tests__/__snapshots__/cell.test.js.snap:419]: Another one of the weird snapshot things. Something to do with tsToJs maybe

File: packages/cli/src/commands/dev.js [hunk 4]
```diff
@@ -101,10 +100,16 @@ export const handler = async ({
       command: `cd "${path.join(
         BASE_DIR,
         'web'
-      )}" && yarn webpack-dev-server --config ../node_modules/@redwoodjs/core/config/webpack.development.js ${forward}`,
+      )}" && yarn cross-env NODE_ENV=development webpack-dev-server --config ../node_modules/@redwoodjs/core/config/webpack.development.js ${forward}`,
```
Comment (dac09) [inline packages/cli/src/commands/dev.js:103]: This will also allow us to use tailwind's JIT without more hassle

File: packages/web/src/global.web-auto-imports.ts [hunk 5]
```diff
@@ -11,4 +11,18 @@ declare global {
...
   }
+
+  // Overridable graphQL hook return types
+  interface QueryOperationResult<TData = any> {
+    data: TData | undefined
+    loading: boolean
+
+    // @TODO Adding error here causes a problem with Apollo, because TS thinks this is the override, not the apollo one
+    // Not really a problem, but the types in createCell aren't a 100% acurate
+    // error?: Error | any
```
Comment (peterp) [inline packages/web/src/global.web-auto-imports.ts:22]: Is this still relevenat?

**Review by peterp — APPROVED** [review]
Two small things that are problems, but overall looks good to me!

**Comment by peterp** [comment]
Let's combine the efforts for creating docs once I've merged my two TS generation PRs.

File: packages/web/src/components/createCell.tsx [hunk 6]
```diff
@@ -1,39 +1,43 @@
-import { useQuery, OperationResult } from './GraphQLHooksProvider'
+import { A } from 'ts-toolbelt'
```
[the remark this answers is not in the document]
Comment (dac09) [reply packages/web/src/components/createCell.tsx:1]: haha not sure what the change here is peter! But yes its a devDep, did you mean import type only?

File: packages/web/src/global.web-auto-imports.ts (hunk 5 above)
Comment (dac09) [reply packages/web/src/global.web-auto-imports.ts]: Done 👍

File: packages/web/src/components/createCell.tsx (hunk 6 above)
[the remark this answers is not in the document]
Comment (dac09) [reply packages/web/src/components/createCell.tsx]: Done 👍

[the remark this answers is not in the document]
Comment (peterp) [reply packages/web/src/components/createCell.tsx]: lol, I don't know why I used the suggestion tool... top-kek!

I mean that because it's a devDependency it won't be installed for users, and it looks like a "design time requirement," basically I'm not sure what the type looks like when it's generated? Does it reference `A` or does it interpolate that value and expand it in the generated type def?
