### PR TITLE
fix(babel-preset): Fix babel loose warnings & SVG import

### LINKED ISSUE #2472: SVGs break RW 0.32.1 in Netlify/TailwindCSS deploy
I originally posted the issue on the Redwood forum [here](https://community.redwoodjs.com/t/redwood-v0-31-0/2066/14?u=isaact8) 

Please see the above link for the error message**s** as they were over 30,000 words...

The issue is that when SVGs are used in my code base I was getting this error:

```
 TypeError: Property value of ObjectProperty expected node to be of a type ["Expression","PatternLike"] but instead got "JSXExpressionContainer" src/pages/AboutPage/AboutPage.js 
```
as well as a few hundred more lines of error messages in my Netlify build and within the console.
--- 
It did not matter if the SVG was rendered through a component or in an image tag the error was still thrown. My temporary work around was to convert the offending image from svg to png and the error went away.

Also, since upgrading to 0.32.1 whenever I run `yarn rw dev` I am getting a lot of `babel` errors in console... Also mentioned in the forum with full text of the warnings in the link above (perhaps this should be a separate issue?).

Thanks to @alecortega (forum user name) who helped point me down the right path towards figuring out what was causing the errors.

### PR DESCRIPTION
**Pull request by dac09**
## What does it do?
- **Configures `plugin-proposal-private-methods` and `plugin-proposal-class-properties` with loose.** 
This is how it was before anyway, but the new babel preset env has it built in, so in order to configure it you have to remove it from the preset-env plugin, and add it manually. These were the many many warnings we were seeing in the console

- **Configures react-inline-svg-plugin for better svg support**
Since the bump to plugin version 2.x there were breaking changes to how SVGs are handled. This attempts to restore backwards compatibility (and prevent errors on certain SVGs ) 

Fixes #2472

### CODE REVIEW

File: packages/core/config/babel-preset.js [hunk 1]
```diff
@@ -55,6 +57,13 @@ module.exports = () => {
                 // List of supported proposals: https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#ecmascript-proposals
                 proposals: true,
               },
+              exclude: [
+                // Although preset-env includes class-properties
+                // but webpack 4 doesn't support the syntax when target supports and babel transpilation is skipped
+                // https://github.com/webpack/webpack/issues/9708
```
Comment (Tobbe) [inline packages/core/config/babel-preset.js:63]: I don't understand this comment. I think the English is too broken 😬 
Can we simplify it to this?
```suggestion
                // Although preset-env includes class-properties webpack 4 doesn't support it.
                // https://github.com/webpack/webpack/issues/9708
```

Comment (dac09) [reply packages/core/config/babel-preset.js:63]: Sure. I copied it :P

File: packages/core/config/babel-preset.js [hunk 2]
```diff
@@ -21,6 +22,7 @@ module.exports = () => {
     presets: ['@babel/preset-react', '@babel/preset-typescript'],
     plugins: [
       ['@babel/plugin-proposal-class-properties', { loose: true }],
+      ['@babel/plugin-proposal-private-methods', { loose: true }],
```
Comment (peterp) [inline packages/core/config/babel-preset.js:25]: Could we add a note here: 
```suggestion
      // Note: The private method loose mode configuration setting must be the
      // same as @babel/plugin-proposal class-properties.
      // (https://babeljs.io/docs/en/babel-plugin-proposal-private-methods#loose)
      ['@babel/plugin-proposal-private-methods', { loose: true }],
```

**Review by peterp — APPROVED** [review]

File: packages/core/config/babel-preset.js [hunk 3]
```diff
@@ -148,7 +162,29 @@ module.exports = () => {
...
+            'inline-react-svg',
+            {
+              svgo: {
+                plugins: extendDefaultPlugins([
+                  {
+                    name: 'removeAttrs',
+                    params: { attrs: '(data-name)' },
+                  },
+                  {
+                    // @TODO confirm this is the right thing
```
Comment (peterp) [inline packages/core/config/babel-preset.js:175]: How do we confirm that this is the right thing?

Comment (dac09) [reply packages/core/config/babel-preset.js:178]: I checked some other svgs from heroicons/feathericons - they seem to include viewBox. For now I'd suggest lets keep it in (because its backwards compatible)
