### PR TITLE
Show authentication errors in <FormError>

### LINKED ISSUE #568: Show authentication errors in <FormError>
Now that we have authentication we need to update the logic in `<FormError>` that tries to determine what GraphQL error occurred and format it nicely for display. Apparently this is a new kind of error completely because the error box shows but is empty:

image

The error in the web inspector looks like:

```json
{
  "errors": [
    {
      "message": "",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createPost"
      ],
      "extensions": {
        "code": "UNAUTHENTICATED",
        "exception": {
          "stacktrace": [
            "AuthenticationError: ",
            "    at requireAuth (/Users/rob/Sites/redwoodjs/hammerblog/api/src/lib/auth.js:9:11)",
            "    at Object.createPost (/Users/rob/Sites/redwoodjs/hammerblog/api/src/services/posts/posts.js:15:3)",
            "    at createPost (/Users/rob/Sites/redwoodjs/hammerblog/node_modules/@redwoodjs/api/src/makeMergedSchema/makeMergedSchema.js:29:11)",
            "    at field.resolve (/Users/rob/Sites/redwoodjs/hammerblog/node_modules/graphql-extensions/src/index.ts:274:18)",
            "    at resolveFieldValueOrError (/Users/rob/Sites/redwoodjs/hammerblog/node_modules/graphql/execution/execute.js:467:18)",
            "    at resolveField (/Users/rob/Sites/redwoodjs/hammerblog/node_modules/graphql/execution/execute.js:434:16)",
            "    at /Users/rob/Sites/redwoodjs/hammerblog/node_modules/graphql/execution/execute.js:244:18",
            "    at /Users/rob/Sites/redwoodjs/hammerblog/node_modules/graphql/jsutils/promiseReduce.js:23:10",
            "    at Array.reduce (<anonymous>)",
            "    at promiseReduce (/Users/rob/Sites/redwoodjs/hammerblog/node_modules/graphql/jsutils/promiseReduce.js:20:17)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

### PR DESCRIPTION
**Pull request by Terris**
Fixes #568 

- Adds a standard auth error message to generated auth.js file
- Adds a fallback root message if rootMessage is empty: "Something went wrong."
- Adds conditional rendering to the Form error messages list.
- Fixes a minor spacing issue in the styles.

### CODE REVIEW

File: packages/web/src/form/form.js [hunk 1]
```diff
@@ -117,19 +117,21 @@ const FormError = ({
       {messages && (
         <div className={wrapperClassName} style={wrapperStyle}>
           <p className={titleClassName} style={titleStyle}>
-            {rootMessage}
+            {rootMessage !== '' ? rootMessage : 'Something went wrong.'}
```
Comment (cannikin) [inline packages/web/src/form/form.js:120]: We're sure that `rootMessage` will always be at least empty string at this point? It's set too `null` originally, and assuming there is a GraphQL or Network error it will be set to those errors...

Comment (Terris) [reply packages/web/src/form/form.js:120]: This is in case GraphQL/Apollo sends back errors but doesn't include a message value which is the exact scenario you were seeing when you got a blank FormError component. For instance, if you don't include a message in `throw new AuthenticationError()` then you'll still get an error object response but the message value (which gets assigned to rootMessage) is a blank string. There are also a further number of errors Apollo could send back without a message ([see here](https://github.com/apollographql/apollo-server/blob/4fb348102e1248f78f6df5c70090147c5ceb7300/packages/apollo-server-errors/src/index.ts#L172)) and, presently, we don't have a way of sorting them out and returning a coherent message. I'd like to take a stab at fixing that soon but I wanted to take care of this instance first as it's an error that might be more common now that auth has been implemented.

**Comment by cannikin** [comment]
Thanks for this!
