### PR TITLE
MockProvider: Wrap children in LocationProvider

### LINKED ISSUE #1676: Running tests on NavLink component throws "TypeError: Cannot read property 'pathname' of undefined"
When running the default generated test on a component that uses a `NavLink` you get a `TypeError: Cannot read property 'pathname' of undefined`. I managed to reproduce this with the following component:
```javascript
import React from "react";
import { routes, NavLink } from "@redwoodjs/router";

const HerculesLayout = (props) => {
  return <NavLink to={routes.home()}>Home</NavLink>;
};

export default HerculesLayout;
```
And the following test which hasn't been modified and was generated by the layout scaffolding:
```javascript
import { render } from "@redwoodjs/testing";

import HerculesLayout from "./HerculesLayout";

describe("HerculesLayout", () => {
  it("renders successfully", () => {
    expect(() => {
      render(<HerculesLayout />);
    }).not.toThrow();
  });
});
```
This gives me the following error in the console when running `yarn rw test`:
```shell
 HerculesLayout
    ✕ renders successfully (96 ms)

  ● HerculesLayout › renders successfully

    expect(received).not.toThrow()

    Error name:    "TypeError"
    Error message: "Cannot read property 'pathname' of undefined"

           6 |   it("renders successfully", () => {
           7 |     expect(() => {
        >  8 |       render(<HerculesLayout />);
             |       ^
           9 |     }).not.toThrow();
          10 |   });
          11 | });

          at useMatch (node_modules/@redwoodjs/router/dist/links.js:32:62)
          at node_modules/@redwoodjs/router/dist/links.js:62:21
          at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14803:18)
          at updateForwardRef (node_modules/react-dom/cjs/react-dom.development.js:16816:20)
          at beginWork (node_modules/react-dom/cjs/react-dom.development.js:18645:16)
          at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:188:14)
          at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
          at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:318:25)
          at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
          at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
          at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
          at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
          at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:237:16)
          at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:292:31)
          at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:23203:7)
          at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22157:12)
          at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22130:22)
          at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:21756:9)
          at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21188:7)
          at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:24373:3)
          at node_modules/react-dom/cjs/react-dom.development.js:24758:7
          at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:21903:12)
          at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:24757:5)
          at Object.render (node_modules/react-dom/cjs/react-dom.development.js:24840:10)
          at node_modules/@testing-library/react/dist/pure.js:99:25
          at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:21856:12)
          at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:929:14)
          at render (node_modules/@testing-library/react/dist/pure.js:95:26)
          at customRender (node_modules/@redwoodjs/testing/dist/customRender.js:20:29)
          at web/src/layouts/HerculesLayout/HerculesLayout.test.js:8:7
          at Object.<anonymous> (node_modules/expect/build/toThrowMatchers.js:83:11)
          at Object.toThrow (node_modules/expect/build/index.js:338:21)
          at Object.<anonymous> (web/src/layouts/HerculesLayout/HerculesLayout.test.js:9:12)

       7 |     expect(() => {
       8 |       render(<HerculesLayout />);
    >  9 |     }).not.toThrow();
         |            ^
      10 |   });
      11 | });
      12 |

      at Object.<anonymous> (src/layouts/HerculesLayout/HerculesLayout.test.js:9:12)
```
The diagnostic info from `yarn rw info` on my machine is:
```shell
yarn run v1.22.10
$ /Users/daniel/Code/node_modules/.bin/rw info

  System:
    OS: macOS 10.15.7
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.3 - /var/folders/qn/40g470191zb8sqvzqhv9r2p80000gn/T/yarn--1611790331077-0.2843548795228614/node
    Yarn: 1.22.10 - /var/folders/qn/40g470191zb8sqvzqhv9r2p80000gn/T/yarn--1611790331077-0.2843548795228614/yarn
  Databases:
    SQLite: 3.28.0 - /usr/bin/sqlite3
  Browsers:
    Firefox: 84.0.2
    Safari: 14.0.2
  npmPackages:
    @redwoodjs/core: 0.23.0 => 0.23.0

✨  Done in 1.50s.
```

### PR DESCRIPTION
**Pull request by Tobbe**
Fixes #1676

### CODE REVIEW

File: packages/testing/src/MockProviders.tsx [hunk 1]
```diff
@@ -6,6 +6,8 @@ import React from 'react'
 
 import { AuthProvider } from '@redwoodjs/auth'
 import type { AuthContextInterface } from '@redwoodjs/auth'
+// @ts-ignore
```
Comment (Tobbe) [inline packages/testing/src/MockProviders.tsx:9]: @peterp I'm not sure what to do here. We use `// @ts-ignore` in MockRouter.tsx, why can't I do that here as well?

Comment (peterp) [reply packages/testing/src/MockProviders.tsx:9]: Maybe try `// @ts-expect-error - <reason why we expect an error>`

Comment (Tobbe) [reply packages/testing/src/MockProviders.tsx]: Thanks!

**Comment by thedavidprice** [comment]
@dac09 how about this one for v0.25 vs v0.26? If v0.25, could you then re-ping Peter's review?

**Comment by dac09** [comment]
Looks clear to me! Will add milestone

File: packages/testing/src/MockProviders.tsx [hunk 2]
```diff
@@ -6,6 +6,8 @@ import React from 'react'
 
 import { AuthProvider } from '@redwoodjs/auth'
 import type { AuthContextInterface } from '@redwoodjs/auth'
+// @ts-expect-error - No module definitions for unexported modules
```
Comment (dac09) [inline packages/testing/src/MockProviders.tsx:9]: No need for this anymore I think! LocationProvider is exported from router :)

File: packages/testing/src/MockProviders.tsx [hunk 3]
```diff
@@ -55,7 +57,7 @@ export const MockProviders: React.FunctionComponent = ({ children }) => {
     <AuthProvider client={mockAuthClient} type="custom">
       <RedwoodApolloProvider useAuth={fakeUseAuth}>
         <UserRouterWithRoutes />
-        {children}
+        <LocationProvider>{children}</LocationProvider>
```
Comment (dac09) [inline packages/testing/src/MockProviders.tsx:60]: Should we pass a mocked location here?

File: package.json [hunk 4]
```diff
@@ -1,5 +1,6 @@
 {
   "scripts": {
+    "prebuild": "lerna run build --scope @redwoodjs/router",
```
Comment (Tobbe) [inline package.json:3]: @peterp How can we do this in a nicer way?

Comment (peterp) [reply package.json:3]: Could you let me know what this is solving? Do you need the typings for another package?

Comment (peterp) [reply package.json:3]: Is it the typing that you require?

Comment (Tobbe) [reply package.json:3]: Without it I get this
image

Comment (Tobbe) [reply package.json:3]: Testing needs stuff from router, but it's building testing first.

If I run the build twice it'll work the second time because then it has the typings from the previous build

Comment (Tobbe) [reply package.json:3]: Solved it! I'll update the PR

File: packages/testing/src/MockProviders.tsx (hunk 3 above)
Comment (Tobbe) [reply packages/testing/src/MockProviders.tsx:59]: I don't think that's needed, at least for now. You get a proper location back when using `useLocation()`. Here's an example screenshot. "/iframe.html" is from `const { pathname } = useLocation()`

image

**Comment by Tobbe** [comment]
@peterp This is ready for your review now. And then I can merge it.

File: packages/testing/tsconfig.json [hunk 5]
```diff
@@ -15,6 +15,7 @@
   "references": [
     { "path": "../internal" },
     { "path": "../web" },
-    { "path": "../auth" }
+    { "path": "../auth" },
+    { "path": "../router" }
```
Comment (peterp) [inline packages/testing/tsconfig.json:19]: 👍

**Review by peterp — APPROVED** [review]
Looks good to me
