### PR TITLE
fix(cli): handle both single and double quotes during dbAuth setup

### LINKED ISSUE #11526: [Bug]: Double quotes for strings fail auth setup command
### What's not working?

If I change prettier settings to use double quotes for strings, then `yarn rw setup auth dbAuth` command fails with "Failed to import cookieName" error.

### How do we reproduce the bug?

1. Generate new project with `yarn create redwood-app my-app --ts` command.
2. In prettier.config.js file set `singleQuote: false`.
3. Run `yarn rw lint --fix` in the command line.
4. Commit the changes.
5. Run `yarn rw setup auth dbAuth` and observe the error:
    image

### What's your environment? (If it applies)

```shell
System:
  OS: macOS 14.5
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.17.0 - /private/var/folders/fn/l_969nyj4bb2j2qcn8qsw2fw0000gn/T/xfs-2b9ea658/node
  Yarn: 4.4.0 - /private/var/folders/fn/l_969nyj4bb2j2qcn8qsw2fw0000gn/T/xfs-2b9ea658/yarn
Databases:
  SQLite: 3.43.2 - /usr/bin/sqlite3
Browsers:
  Safari: 17.5
npmPackages:
  @redwoodjs/auth-dbauth-setup: 8.1.0 => 8.1.0
  @redwoodjs/core: 8.1.0 => 8.1.0
  @redwoodjs/project-config: 8.1.0 => 8.1.0
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

### PR DESCRIPTION
**Pull request by Josh-Walker-GM**
Fixes #11526. 

We had a few find and replaces which don't work if you elect to have double quotes rather than single quotes.

By default we ship with a config that expects single quotes so I am not going to audit the entire cli/framework in this PR to ensure we support double quotes at all times. This addresses the issue and so I think is good enough for now. A lot of these functions are utilities so editing them here should have good coverage in other commands.

### CODE REVIEW

File: packages/cli-helpers/src/auth/authTasks.ts [hunk 1]
```diff
@@ -154,7 +154,7 @@ const addAuthImportToRoutes = (content: string) => {
   const contentLines = content.split('\n')
   // Find the last import line that's not a .css or .scss import
   const importIndex = contentLines.findLastIndex((line: string) =>
-    /^\s*import (?!.*(?:.css'|.scss'))/.test(line),
+    /^\s*import (?!.*(?:.css['"]|.scss['"]))/.test(line),
```
Comment (Josh-Walker-GM) [inline packages/cli-helpers/src/auth/authTasks.ts:157]: You could probably write a regex that makes sure the opening and closing quotes are the same - as they would be. I don't think we need to be that surgical here and now.

Comment (Tobbe) [reply packages/cli-helpers/src/auth/authTasks.ts:157]: We could. And we don't have to. But if we wanted it'd be very easy 😉  Just create a capture group and then back-reference it 🙂

Comment (Tobbe) [reply packages/cli-helpers/src/auth/authTasks.ts:157]: `/(b)\1/i.test("bB"); // true`

Comment (Josh-Walker-GM) [reply packages/cli-helpers/src/auth/authTasks.ts:157]: Hahah if you want to push up a commit for it then happy for you too 😉 but otherwise I'm not going to 😆

**Review by Tobbe — APPROVED** [review]
LGTM
