### PR TITLE
fix(rw-eslint): Implement more specific checking on Routes

### LINKED ISSUE #10383: [Bug]: Routes eslint targets too many elements
In packages/eslint-plugin/src/__tests__/unsupported-route-components.test.ts our linting is too broad, it targets _all_ JSX opening elements. 

Image

**Expected behaviour:**
If you use any other elements outside the Route tree it should not throw a linting error or warning

### PR DESCRIPTION
**Pull request by dac09**
Fixes #10383

See issue for more details. 

This change does the following:
1. Searches for the return statement from the `Routes` component
2. If the body contains JSXElements, check each JSXElement and it's children recursively

Point (1) is the real fix. Technically, you could call your `Routes` component something else though, and this linter won't catch it - but it won't break either.

### CODE REVIEW

File: packages/eslint-plugin/src/unsupported-route-components.ts [hunk 1]
```diff
@@ -18,28 +42,42 @@ export const unsupportedRouteComponents = createRule({
       unexpected:
         'Unexpected JSX element <{{name}}>. Only <Router>, <Route>, <Set>, <PrivateSet> and <Private> are allowed in the Routes file.',
```
Comment (Tobbe) [inline packages/eslint-plugin/src/unsupported-route-components.ts:43]: Do we need to change the error message to be more specific too?

File: packages/eslint-plugin/src/unsupported-route-components.ts [hunk 2]
```diff
@@ -7,6 +8,29 @@ function isAllowedElement(name: string) {
   return allowedElements.includes(name)
 }
 
+function checkNodes(
+  nodesToCheck: TSESTree.JSXElement | TSESTree.JSXChild,
+  context: any,
```
Comment (Tobbe) [inline packages/eslint-plugin/src/unsupported-route-components.ts:13]: Is there a better type you could use here?

Comment (dac09) [reply packages/eslint-plugin/src/unsupported-route-components.ts:13]: Ah yes, I forgot to take this out. Let me see if I can find the Eslint context.

File: packages/eslint-plugin/src/__tests__/unsupported-route-components.test.ts [hunk 3]
```diff
@@ -38,12 +38,32 @@ ruleTester.run('unsupported-route-components', unsupportedRouteComponents, {
...
     },
+    {
+      code: `
+        const AnotherThing = <Bazinga><p>Hello</p></Bazinga>
+        const Routes = () => {
+          return (
+            <Router>
+              <PrivateSet
+              whileLoadingAuth={AnotherThing}
+              >
```
Comment (Tobbe) [inline packages/eslint-plugin/src/__tests__/unsupported-route-components.test.ts:49]: Sorry about the nitpicking here, but could you put all of this on one line?

File: packages/eslint-plugin/src/unsupported-route-components.ts (hunk 1 above)
Comment (dac09) [reply packages/eslint-plugin/src/unsupported-route-components.ts:44]: No I don't think so, because the problem was that it was targetting all JSX Elements.  The behaviour actually hasn't changed

Comment (Tobbe) [reply packages/eslint-plugin/src/unsupported-route-components.ts:44]: > Only <Router>, <Route>, <Set>, <PrivateSet> and <Private> are allowed in the Routes file.

It's not true though, is it? You can have `const AnotherThing = <Bazinga><p>Hello</p></Bazinga>` in your Routes file and it's still perfectly valid, right? We just want to warn against doing crazy things inside the `<Router>` element itself, not the entire file.

File: packages/eslint-plugin/src/__tests__/unsupported-route-components.test.ts (hunk 3 above)
Comment (Tobbe) [reply packages/eslint-plugin/src/__tests__/unsupported-route-components.test.ts]: image
 😄  This made me smile

File: packages/eslint-plugin/src/unsupported-route-components.ts (hunk 1 above)
Comment (dac09) [reply packages/eslint-plugin/src/unsupported-route-components.ts:44]: Oh I see what you're saying!

Comment (dac09) [reply packages/eslint-plugin/src/unsupported-route-components.ts]: Updated!

**Review by Tobbe — APPROVED** [review]

**Comment by jtoar** [comment]
Marking this one as next release major since it builds on https://github.com/redwoodjs/redwood/pull/10266 and isn't trivial to cherry pick over
