### PR TITLE
Passthrough error codes on cli failures

### LINKED ISSUE #1788: Exit status code is always zero for failed test in yarn rw test
When running `yarn rw test --no-watch` the status code is zero even if tests have failed. The output log states that the command failed with an exit code of 1 but upon inspecting the last command exit code (via `echo $?`) it's still zero. 

image

Associated Redwood info:
```shell
 » yarn rw info
yarn run v1.22.10
$ /Users/daniel/Code/LoopUp/sherwood/sherwood-admin-ticket-portal/node_modules/.bin/rw info

  System:
    OS: macOS 10.15.7
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.3 - /var/folders/qn/40g470191zb8sqvzqhv9r2p80000gn/T/yarn--1613179197434-0.3059933859284285/node
    Yarn: 1.22.10 - /var/folders/qn/40g470191zb8sqvzqhv9r2p80000gn/T/yarn--1613179197434-0.3059933859284285/yarn
  Databases:
    SQLite: 3.28.0 - /usr/bin/sqlite3
  Browsers:
    Firefox: 85.0
    Safari: 14.0.3
  npmPackages:
    @redwoodjs/core: 0.23.0 => 0.23.0

✨  Done in 3.14s.
```

### PR DESCRIPTION
**Pull request by dac09**
Fixes #1788

### What?
Makes sure:
**a) `yarn test` waits for execa to execute**
if we don't have the await, the error isn't really captured
(Note: unrelated, but it seems my fresh 0.25 project gets test failures, probably due to the graphql provider changes)

**b) Bunch of other commands actually exit with the correct error code** 

### Why?
Because most of our CLI commands are in  try catch blocks, it swallows the exit codes if we don't explicitly exit with a code.

### CODE REVIEW

**Comment by dac09** [comment]
@thedavidprice, do we want this in the hotfix?

@cannikin I'm not super sure about dataMigrate up and the finally block. Any thoughts? I noticed this issue right since `yarn rw dm` was introduced, but I thought I was doing something wrong.

**Comment by dthyresson** [comment]
See also https://github.com/redwoodjs/redwood/issues/1794

File: packages/cli/src/commands/test.js [hunk 1]
```diff
@@ -100,7 +99,7 @@ export const handler = async ({
 
     // Create a test database
     if (sides.includes('api')) {
-      await execa.command(`yarn rw prisma db push --force`, {
+      await execa(`yarn rw prisma db push --force`, {
```
Comment (dac09) [inline packages/cli/src/commands/test.js:102]: The `.command` breaks tests in the contributor workflow. 🤷🏾‍♂️ Probably due to execa resolving wrongly.

File: packages/cli/src/commands/dataMigrate/up.js [hunk 2]
```diff
@@ -155,9 +155,11 @@ export const handler = async () => {
 
   try {
     await tasks.run()
+    process.exit(0)
```
Comment (peterp) [inline packages/cli/src/commands/dataMigrate/up.js:158]: I think this would prevent the finally block, I don't think exiting here is the right thing to do.

File: packages/cli/src/commands/upgrade.js [hunk 3]
```diff
@@ -246,5 +246,6 @@ export const handler = async ({ d, tag, pr }) => {
     await tasks.run()
   } catch (e) {
     console.log(c.error(e.message))
```
Comment (peterp) [inline packages/cli/src/commands/upgrade.js:248]: Use stderr, instead of stdout.
```suggestion
    console.error(c.error(e.message))
```

File: packages/cli/src/commands/setup/webpack/webpack.js [hunk 4]
```diff
@@ -56,5 +56,6 @@ export const handler = async ({ force }) => {
     await tasks.run()
   } catch (e) {
     console.log(c.error(e.message))
```
Comment (peterp) [inline packages/cli/src/commands/setup/webpack/webpack.js:58]: Use stderr, instead of stdout.
```suggestion
    console.error(c.error(e.message))
```

File: packages/cli/src/commands/setup/tailwind/tailwind.js [hunk 5]
```diff
@@ -191,5 +191,6 @@ export const handler = async ({ force }) => {
     await tasks.run()
   } catch (e) {
     console.log(c.error(e.message))
```
Comment (peterp) [inline packages/cli/src/commands/setup/tailwind/tailwind.js:193]: Use stderr, instead of stdout.
```suggestion
    console.error(c.error(e.message))
```

File: packages/cli/src/commands/setup/i18n/i18n.js [hunk 6]
```diff
@@ -91,5 +91,6 @@ export const handler = async ({ force }) => {
     await tasks.run()
   } catch (e) {
     console.log(c.error(e.message))
```
Comment (peterp) [inline packages/cli/src/commands/setup/i18n/i18n.js:93]: Use stderr, instead of stdout.
```suggestion
    console.error(c.error(e.message))
```

File: packages/cli/src/commands/setup/deploy/deploy.js [hunk 7]
```diff
@@ -160,5 +160,6 @@ export const handler = async ({ provider, force }) => {
     await tasks.run()
   } catch (e) {
     console.log(c.error(e.message))
```
Comment (peterp) [inline packages/cli/src/commands/setup/deploy/deploy.js:162]: Use stderr, instead of stdout.
```suggestion
    console.error(c.error(e.message))
```

File: packages/cli/src/commands/setup/auth/auth.js [hunk 8]
```diff
@@ -308,5 +308,6 @@ export const handler = async ({ provider, force }) => {
     await tasks.run()
   } catch (e) {
     console.log(c.error(e.message))
```
Comment (peterp) [inline packages/cli/src/commands/setup/auth/auth.js:310]: Use stderr, instead of stdout.
```suggestion
    console.error(c.error(e.message))
```

File: packages/cli/src/commands/generate/sdl/sdl.js [hunk 9]
```diff
@@ -234,5 +234,6 @@ export const handler = async ({
     await tasks.run()
   } catch (e) {
     console.log(c.error(e.message))
```
Comment (peterp) [inline packages/cli/src/commands/generate/sdl/sdl.js:236]: Use stderr, instead of stdout.
```suggestion
    console.error(c.error(e.message))
```

File: packages/cli/src/commands/generate/page/page.js [hunk 10]
```diff
@@ -197,5 +197,6 @@ export const handler = async ({
     await tasks.run()
   } catch (e) {
     console.log(c.error(e.message))
```
Comment (peterp) [inline packages/cli/src/commands/generate/page/page.js:199]: Use stderr, instead of stdout.
```suggestion
    console.error(c.error(e.message))
```

File: packages/cli/src/commands/generate/helpers.js [hunk 11]
```diff
@@ -125,6 +125,7 @@ export const createYargsForComponentGeneration = ({
         await tasks.run()
       } catch (e) {
         console.log(c.error(e.message))
```
Comment (peterp) [inline packages/cli/src/commands/generate/helpers.js:127]: Use stderr, instead of stdout.
```suggestion
        console.error(c.error(e.message))
```

File: packages/cli/src/commands/dataMigrate/up.js (hunk 2 above)
Comment (peterp) [inline packages/cli/src/commands/dataMigrate/up.js:158]:
```suggestion
```

File: packages/cli/src/commands/dataMigrate/install.js [hunk 12]
```diff
@@ -87,5 +87,6 @@ export const handler = async () => {
     await tasks.run()
   } catch (e) {
     console.log(c.error(e.message))
```
Comment (peterp) [inline packages/cli/src/commands/dataMigrate/install.js:89]: Use stderr, instead of stdout
```suggestion
    console.error(c.error(e.message))
```

**Review by peterp — CHANGES_REQUESTED** [review]
Nice, thanks for doing this! Since we're already here just a few requests for using stderr instead of stdout.

And the removal of process.exit(0).

File: packages/cli/src/commands/dataMigrate/up.js (hunk 2 above)
Comment (dac09) [reply packages/cli/src/commands/dataMigrate/up.js:158]: Hmmm you're right!

**Comment by dac09** [comment]
All done @peterp, thanks for the review!

File: packages/cli/src/commands/dataMigrate/up.js [hunk 13]
```diff
@@ -155,9 +155,11 @@ export const handler = async () => {
...
   try {
     await tasks.run()
-  } finally {
     await db.$disconnect()
     report(counters)
-    process.exit(0)
+  } catch (e) {
+    await db.$disconnect()
+    report(counters)
+    process.exit(e?.exitCode || 1)
```
Comment (peterp) [inline packages/cli/src/commands/dataMigrate/up.js:163]: The `finally` block was really elegant, but this get the job done too.

Comment (dac09) [reply packages/cli/src/commands/dataMigrate/up.js:163]: I know :(, but process.exit in the catch would mean it wouldn't run!

**Review by peterp — APPROVED** [review]

**Review by thedavidprice — APPROVED** [review]
🚀

**Comment by thedavidprice** [comment]
tested locally = ✅
