### PR TITLE
fix: generated relational arrays

### LINKED ISSUE #740: Scaffold generator not generating scalar arrays in SDL
So I am not sure if I am doing something wrong or if this is an issue. When I generate a scaffold for one of my types called a farm see schema:

```
model Farm {
  createdAt               DateTime    @default(now())
  description             String?
  farmers                 String?
  founded                 Int?
  id                      Int         @id @default(autoincrement())
  laborSource             String?
  name                    String      @unique
  otherCertifications     String
  partnerSince            Int?
  safetyCertifications    String
  size                    String?
  sustainabilityPractices String
  updatedAt               DateTime    @default(now())
  url                     String?
  city                    String
  lat                     Float?
  lng                     Float?
  state                   String
  street                  String
  zip                     Int
  logo                    String
  images                  String[]
  Inventories             Inventory[] @relation(references: [id])
}
```

The resulting SDL does acknowledge the string array:

```
export const schema = gql`
  type Farm {
    createdAt: DateTime!
    description: String
    farmers: String
    founded: Int
    id: Int!
    laborSource: String
    name: String!
    otherCertifications: String!
    partnerSince: Int
    safetyCertifications: String!
    size: String
    sustainabilityPractices: String!
    updatedAt: DateTime!
    url: String
    city: String!
    lat: Float
    lng: Float
    state: String!
    street: String!
    zip: Int!
    logo: String!
    images: String      // <----- This should be an array
    Inventories: Inventory
  }
...
```

This causes the error 

```
TypeError: String cannot represent value: ["https://res.c ..."]
```

Is this expected behavior and we should modify the sdl manually? Could I have setup something incorrectly?

Manually changing the SDL to:

```
...
images: [String]
...
```

fixes this for me.

You will also notice the generated Inventories field based on related model behaves similarly.

### LINKED ISSUE #741: Scaffold generator not generating arrays for relations
Similar to #740 it appears the SDL generator is not properly generating the array syntax for `@relation` fields.

```
model Farm {
  createdAt    DateTime    @default(now())
  id           Int         @id @default(autoincrement())
  Inventories  Inventory[] @relation(references: [id])
}
```

Is generating:

```
export const schema = gql`
  type Farm {
    createdAt: DateTime!
    id: Int!
    Inventories: Inventory  // <---
  }
```

When it should be:

```
export const schema = gql`
  type Farm {
    createdAt: DateTime!
    id: Int!
    Inventories: Inventory[]  // <---
  }
```

### PR DESCRIPTION
**Pull request by Rosenberg96**
Closes #741 
Closes #740 

Ammends #747 

This PR fixes the format of the generated relational arrays

### CODE REVIEW

File: packages/cli/src/commands/generate/sdl/__tests__/fixtures/singleWordSdl.js [hunk 1]
```diff
@@ -6,7 +6,7 @@ export const schema = gql`
     name: String
     email: String!
     isAdmin: Boolean!
-    profiles: UserProfile[]
+    profiles: [UserProfile]
```
Comment (mohsen1) [inline packages/cli/src/commands/generate/sdl/__tests__/fixtures/singleWordSdl.js:9]: This means profiles is a nullable list of nullable `UserProfile` items. I'm guessing the list itself is not nullable and at least you get an empty array. (`[UserProfile]!`).

Comment (Rosenberg96) [reply packages/cli/src/commands/generate/sdl/__tests__/fixtures/singleWordSdl.js]: From this [reference](https://github.com/prisma/prisma/issues/847) I think you are correct. I am however a bit confused to the `field.isRequired`, since `[UserProfile!]!' is also valid, but what does the property refer to?

I added the `!` to the `profiles` field.

**Comment by mohsen1** [comment]
Here is how it works:

```graphql
foo: String
```
is `foo: string | null`

```graphql
foo: String!
```
is `foo: string`

```graphql
foo: [String]
```
is `foo: (string | null)[] | null`


```graphql
foo: [String]!
```
is `foo: (string | null)[]`


```graphql
foo: [String!]!
```
is `foo: string[]`

**Comment by cannikin** [comment]
Thanks for that fix !
