### PR TITLE
CurrentUser: Let declaration merging add `roles`

### LINKED ISSUE #7359: [Bug]: CurrentUser can't be declaration merged in RW v4 rc
### What's not working?

image
image

The declaration merging that happens thanks to `all-currentUser.d.ts` causes a type error on `CurrentUser` in `node_modules/@redwoodjs/auth/dist/AuthContext.d.ts`, further causing problems in a user's project when trying to use a stricter definition of `roles`

### How do we reproduce the bug?

Return a stricter definition of `roles` in the return value of `getCurrentUser` in `api/src/lib/auth.ts`

image

And then try to use it
image

### What's your environment? (If it applies)

_No response_

### Are you interested in working on this?

- [X] I'm interested in working on this

### PR DESCRIPTION
**Pull request by Tobbe**
Fixes #7359 

By not declaring `roles` on the "base" `CurrentUser` we give full flexibility to `getCurrentUser` in the user's project to define `roles` however it wants.

### CODE REVIEW

File: packages/internal/src/generate/templates/all-currentUser.d.ts.template [hunk 1]
```diff
@@ -3,8 +3,7 @@ import '@redwoodjs/auth'
 
 import { getCurrentUser } from '../../../api/src/lib/auth'
 
-type ThenArg<T> = T extends PromiseLike<infer U> ? U : T
-export type InferredCurrentUser = ThenArg<ReturnType<typeof getCurrentUser>>
+export type InferredCurrentUser = Awaited<ReturnType<typeof getCurrentUser>>
```
Comment (Tobbe) [inline packages/internal/src/generate/templates/all-currentUser.d.ts.template:6]: This has nothing whatsoever to do with the fix. I just stumbled upon this when looking into the CurrentUser declaration merging and couldn't resist simplifying it a bit like this 🙂

File: packages/auth/src/AuthContext.ts [hunk 2]
```diff
@@ -1,7 +1,6 @@
 import React from 'react'
 
 export interface CurrentUser {
-  roles?: Array<string> | string
```
Comment (Tobbe) [inline packages/auth/src/AuthContext.ts:4]: `roles` will be added by `all-currentUser.d.ts`
