### PR TITLE
More helpful prerender error message

### LINKED ISSUE #6239: [Bug?]: Improve prerender error message
### What's not working?

I think we could improve the error message you get when prerendering fails in some scenarios. 

This is what I see now

image

Like, "What do you mean 'token R'?"

### How do we reproduce the bug?

_No response_

### What's your environment? (If it applies)

_No response_

### Are you interested in working on this?

- [X] I'm interested in working on this

### PR DESCRIPTION
**Pull request by Tobbe**
Fixes #6239 

Before:
before

After:
after

### CODE REVIEW

File: packages/prerender/src/errors.tsx [hunk 1]
```diff
@@ -1,3 +1,5 @@
+import { DocumentNode, print } from 'graphql'
```
Comment (dac09) [inline packages/prerender/src/errors.tsx:1]: Graphql should probably be a dependency here.

File: packages/prerender/src/errors.tsx [hunk 2]
```diff
@@ -23,3 +25,24 @@ export class GqlHandlerImportError {
...
+  variables?: Record<string, unknown>
+  result: string
+}
+
+export class JSONParseError extends Error {
+  constructor({ query, variables, result }: JSONParseErrorArgs) {
+    const message =
+      'Could not parse the GraphQL response.' +
+      '\n  Request: ' +
+      print(query).split('\n').join('\n  ') +
```
Comment (dac09) [inline packages/prerender/src/errors.tsx:40]: Possibly OK to just print the request name here? The query itself can get quite large and may be confusing.

File: packages/prerender/src/errors.tsx (hunk 1 above)
Comment (Tobbe) [reply packages/prerender/src/errors.tsx:1]: I added it as a dev dependency.

File: packages/prerender/src/errors.tsx (hunk 2 above)
Comment (Tobbe) [reply packages/prerender/src/errors.tsx:40]: I wanted to print the whole request to give as much context as possible without forcing the developer to go hunt for the exact query in their source code. Where the query will be equally large and confusing anyway.

Also give the developer more confidence that that's the exact query that was executed.

File: packages/prerender/src/errors.tsx (hunk 1 above)
Comment (dac09) [reply packages/prerender/src/errors.tsx:1]: Has to be dependency I'm afraid. Dev dependency is for us, dependency is for framework users.

File: packages/prerender/src/errors.tsx (hunk 2 above)
Comment (dac09) [reply packages/prerender/src/errors.tsx:40]: Sure - don't think there's a "correct" answer here anyway. I just thought it might be confusing to see a large query there.

**Review by dac09 — APPROVED** [review]
